using HTBAM.Api.Support;
using HTBAM.Application.Interfaces;
using HTBAM.Domain.Entities;
using HTBAM.Infrastructure.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
namespace HTBAM.Api.Controllers;

[ApiController, Authorize(Roles = "ADMIN"), Route("api/admin/users")]
public sealed class AdminUsersController(AppDbContext db, IAuditService audit) : ControllerBase
{
    [HttpGet] public async Task<ActionResult> List([FromQuery] string? q, CancellationToken ct) { var x = db.UsersSet.AsNoTracking().Include(u => u.UserRoles).ThenInclude(r => r.Role).AsQueryable(); if (!string.IsNullOrWhiteSpace(q)) { var k = q.Trim(); x = x.Where(u => u.UserName.Contains(k) || u.FullName.Contains(k) || u.Email.Contains(k)); } return Ok(await x.OrderBy(u => u.UserName).Select(u => new { u.Id, u.UserName, u.Email, u.FullName, u.Status, u.TokenVersion, u.LastLoginAt, u.CreatedAt, Roles = u.UserRoles.Select(r => r.Role.Name) }).ToListAsync(ct)); }
    [HttpGet("roles")] public async Task<ActionResult> Roles(CancellationToken ct) => Ok(await db.RolesSet.AsNoTracking().OrderBy(x => x.Name).ToListAsync(ct));
    public record CreateReq(string UserName, string Email, string FullName, string Password, string[] Roles);
    [HttpPost] public async Task<ActionResult> Create(CreateReq r, CancellationToken ct) { var username = r.UserName.Trim(); var email = r.Email.Trim(); if (string.IsNullOrWhiteSpace(username) || string.IsNullOrWhiteSpace(r.FullName)) return BadRequest("Thiếu tên đăng nhập hoặc họ tên."); if (!Strong(r.Password)) return BadRequest("Mật khẩu phải có ít nhất 10 ký tự, gồm chữ hoa, chữ thường, số và ký tự đặc biệt."); var conflicts = new List<ApiFieldError>(); if (await db.UsersSet.AnyAsync(x => x.UserName.ToUpper() == ApiValidation.Key(username), ct)) conflicts.Add(new ApiFieldError("userName", $"Tên đăng nhập {username} đã tồn tại.")); if (email.Length > 0 && await db.UsersSet.AnyAsync(x => x.Email != "" && x.Email.ToUpper() == ApiValidation.Key(email), ct)) conflicts.Add(new ApiFieldError("email", "Email này đã được sử dụng.")); if (conflicts.Count > 1) return Conflict(ApiValidation.DuplicateFields(conflicts)); if (conflicts.Count == 1) { var conflict = conflicts[0]; return Conflict(ApiValidation.Duplicate(conflict.Field == "userName" ? "USER_NAME_DUPLICATE" : "USER_EMAIL_DUPLICATE", conflict.Field, conflict.Message)); } var roles = await ResolveRoles(r.Roles, ct); if (roles is null) return BadRequest("Vai trò không hợp lệ."); var u = new User { UserName = username, Email = email, FullName = r.FullName.Trim(), Status = "ACTIVE" }; u.PasswordHash = new PasswordHasher<User>().HashPassword(u, r.Password); db.UsersSet.Add(u); await db.SaveChangesAsync(ct); foreach (var role in roles) db.UserRoles.Add(new UserRole { UserId = u.Id, RoleId = role.Id }); await db.SaveChangesAsync(ct); await audit.WriteAsync(UserContext.Id(User), "USER_CREATE", "User", u.Id.ToString(), new { u.UserName, Roles = roles.Select(x => x.Name) }, ct); return Ok(new { u.Id, u.UserName, u.Email, u.FullName }); }
    public record UpdateReq(string Email, string FullName, string[] Roles);
    [HttpPut("{id:long}")] public async Task<ActionResult> Update(long id, UpdateReq r, CancellationToken ct) { var u = await db.UsersSet.Include(x => x.UserRoles).FirstOrDefaultAsync(x => x.Id == id, ct); if (u is null) return NotFound(); var email = r.Email.Trim(); if (!string.IsNullOrEmpty(email) && await db.UsersSet.AnyAsync(x => x.Id != id && x.Email != "" && x.Email.ToUpper() == ApiValidation.Key(email), ct)) return Conflict(ApiValidation.Duplicate("USER_EMAIL_DUPLICATE", "email", "Email này đã được sử dụng.")); var roles = await ResolveRoles(r.Roles, ct); if (roles is null) return BadRequest("Vai trò không hợp lệ."); u.Email = email; u.FullName = r.FullName.Trim(); db.UserRoles.RemoveRange(u.UserRoles); foreach (var role in roles) db.UserRoles.Add(new UserRole { UserId = id, RoleId = role.Id }); u.TokenVersion++; await db.SaveChangesAsync(ct); await audit.WriteAsync(UserContext.Id(User), "USER_UPDATE", "User", id.ToString(), new { Roles = roles.Select(x => x.Name) }, ct); return NoContent(); }
    public record StatusReq(string Status);
    [HttpPut("{id:long}/status")] public async Task<ActionResult> Status(long id, StatusReq r, CancellationToken ct) { var u = await db.UsersSet.FindAsync([id], ct); if (u is null) return NotFound(); var status = r.Status.Trim().ToUpperInvariant(); if (status is not ("ACTIVE" or "LOCKED" or "INACTIVE")) return BadRequest("Trạng thái không hợp lệ."); if (id == UserContext.Id(User) && status != "ACTIVE") return BadRequest("Không thể khóa chính tài khoản đang đăng nhập."); u.Status = status; u.TokenVersion++; await db.SaveChangesAsync(ct); await audit.WriteAsync(UserContext.Id(User), "USER_STATUS_CHANGE", "User", id.ToString(), new { status }, ct); return NoContent(); }
    public record ResetPasswordReq(string NewPassword);
    [HttpPost("{id:long}/reset-password")] public async Task<ActionResult> ResetPassword(long id, ResetPasswordReq r, CancellationToken ct) { if (!Strong(r.NewPassword)) return BadRequest("Mật khẩu chưa đủ mạnh."); var u = await db.UsersSet.FindAsync([id], ct); if (u is null) return NotFound(); u.PasswordHash = new PasswordHasher<User>().HashPassword(u, r.NewPassword); u.TokenVersion++; await db.SaveChangesAsync(ct); await audit.WriteAsync(UserContext.Id(User), "USER_RESET_PASSWORD", "User", id.ToString(), null, ct); return NoContent(); }
    private async Task<List<Role>?> ResolveRoles(string[] requested, CancellationToken ct) { var names = requested.Select(x => x.Trim().ToUpperInvariant()).Where(x => x is "ADMIN" or "LECTURER" or "TECH_AI").Distinct().ToArray(); if (names.Length == 0 || names.Length != requested.Distinct(StringComparer.OrdinalIgnoreCase).Count()) return null; var roles = await db.RolesSet.Where(x => names.Contains(x.Name)).ToListAsync(ct); return roles.Count == names.Length ? roles : null; }
    private static bool Strong(string p) => p.Length >= 10 && p.Any(char.IsUpper) && p.Any(char.IsLower) && p.Any(char.IsDigit) && p.Any(ch => !char.IsLetterOrDigit(ch));
}
