using HTBAM.Api.Support; using HTBAM.Application.Interfaces; using HTBAM.Domain.Entities; using HTBAM.Infrastructure.Data; using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
namespace HTBAM.Api.Controllers;
[ApiController,Authorize,Route("api/attendance-policies")]
public sealed class AttendancePoliciesController(AppDbContext db,IAuditService audit):ControllerBase
{
 [HttpGet]public async Task<ActionResult> List(CancellationToken ct)=>Ok(await db.AttendancePoliciesSet.AsNoTracking().OrderBy(x=>x.Code).ToListAsync(ct));
 public record Req(string Code,string Name,decimal PresentThreshold,decimal PartialThreshold,decimal PresentScore,decimal PartialScore,decimal AbsentScore,string Version,bool IsActive=true);
 [HttpPost,Authorize(Roles="LECTURER")]public async Task<ActionResult> Create(Req r,CancellationToken ct){if(!await IsFacultyHead(ct))return Forbid();var err=Validate(r);if(err!=null)return BadRequest(err);if(await db.AttendancePoliciesSet.AnyAsync(x=>x.Code==r.Code.Trim().ToUpper(),ct))return Conflict("Trùng mã chính sách.");var x=new AttendancePolicy{Code=r.Code.Trim().ToUpper(),Name=r.Name.Trim(),PresentThreshold=r.PresentThreshold,PartialThreshold=r.PartialThreshold,PresentScore=r.PresentScore,PartialScore=r.PartialScore,AbsentScore=r.AbsentScore,Version=r.Version.Trim(),IsActive=r.IsActive};db.AttendancePoliciesSet.Add(x);await db.SaveChangesAsync(ct);await audit.WriteAsync(UserContext.Id(User),"ATTENDANCE_POLICY_CREATE","AttendancePolicy",x.Id.ToString(),new{x.Code},ct);return Ok(x);}
 [HttpPut("{id:long}"),Authorize(Roles="LECTURER")]public async Task<ActionResult> Update(long id,Req r,CancellationToken ct){if(!await IsFacultyHead(ct))return Forbid();var x=await db.AttendancePoliciesSet.FindAsync([id],ct);if(x is null)return NotFound();var err=Validate(r);if(err!=null)return BadRequest(err);if(await db.AttendancePoliciesSet.AnyAsync(y=>y.Id!=id&&y.Code==r.Code.Trim().ToUpper(),ct))return Conflict("Trùng mã chính sách.");x.Code=r.Code.Trim().ToUpper();x.Name=r.Name.Trim();x.PresentThreshold=r.PresentThreshold;x.PartialThreshold=r.PartialThreshold;x.PresentScore=r.PresentScore;x.PartialScore=r.PartialScore;x.AbsentScore=r.AbsentScore;x.Version=r.Version.Trim();x.IsActive=r.IsActive;await db.SaveChangesAsync(ct);await audit.WriteAsync(UserContext.Id(User),"ATTENDANCE_POLICY_UPDATE","AttendancePolicy",id.ToString(),new{x.Code},ct);return NoContent();}
 private async Task<bool> IsFacultyHead(CancellationToken ct){var tid=await AccessScope.TeacherIdAsync(db,User,ct);return tid is >0&&await db.ManagementAssignmentsSet.AnyAsync(x=>x.TeacherId==tid&&x.IsActive&&x.PositionType=="FACULTY_HEAD",ct);}
 private static string? Validate(Req r){if(r.PresentThreshold is <0 or >1||r.PartialThreshold is <0 or >1||r.PresentThreshold<r.PartialThreshold)return "Ngưỡng chuyên cần không hợp lệ.";if(string.IsNullOrWhiteSpace(r.Version))return "Thiếu version.";return null;}
}
