using System.Security.Claims; using HTBAM.Api.Support; using HTBAM.Application.DTOs; using HTBAM.Application.Interfaces; using HTBAM.Infrastructure.Data; using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Identity; using Microsoft.AspNetCore.Mvc; using Microsoft.AspNetCore.RateLimiting; using Microsoft.EntityFrameworkCore;
namespace HTBAM.Api.Controllers;
[ApiController,Route("api/auth")]
public sealed class AuthController(AppDbContext db,ITokenService tokens,IAuditService audit):ControllerBase
{
 [HttpPost("login"),EnableRateLimiting("auth")]
 public async Task<ActionResult<LoginResponse>> Login(LoginRequest req,CancellationToken ct){var key=req.UserName.Trim();var normalizedKey=ApiValidation.Key(key);var user=await db.UsersSet.Include(x=>x.UserRoles).ThenInclude(x=>x.Role).FirstOrDefaultAsync(x=>x.UserName.ToUpper()==normalizedKey||x.Email.ToUpper()==normalizedKey,ct);if(user is null){await audit.WriteAsync(null,"LOGIN_FAILED","User","unknown",new{reason="INVALID_ACCOUNT"},ct);return InvalidCredentials();}if(user.Status!="ACTIVE"){await audit.WriteAsync(user.Id,"LOGIN_FAILED","User",user.Id.ToString(),new{reason="ACCOUNT_LOCKED"},ct);return InvalidCredentials();}if(new PasswordHasher<HTBAM.Domain.Entities.User>().VerifyHashedPassword(user,user.PasswordHash,req.Password)==PasswordVerificationResult.Failed){await audit.WriteAsync(user.Id,"LOGIN_FAILED","User",user.Id.ToString(),new{reason="BAD_PASSWORD"},ct);return InvalidCredentials();}user.LastLoginAt=DateTime.UtcNow;await db.SaveChangesAsync(ct);await audit.WriteAsync(user.Id,"LOGIN_SUCCESS","User",user.Id.ToString(),null,ct);return Ok(tokens.Create(user,user.UserRoles.Select(x=>x.Role.Name).ToArray()));}
 public record ChangePasswordRequest(string CurrentPassword,string NewPassword);
 [Authorize,HttpPut("change-password")]
 public async Task<ActionResult> ChangePassword(ChangePasswordRequest req,CancellationToken ct){if(!long.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier),out var id))return Unauthorized();var user=await db.UsersSet.FindAsync([id],ct);if(user is null)return Unauthorized();var hasher=new PasswordHasher<HTBAM.Domain.Entities.User>();if(hasher.VerifyHashedPassword(user,user.PasswordHash,req.CurrentPassword)==PasswordVerificationResult.Failed)return BadRequest("Mật khẩu hiện tại không đúng.");if(!Strong(req.NewPassword))return BadRequest("Mật khẩu >=10 ký tự, có hoa, thường, số và ký tự đặc biệt.");user.PasswordHash=hasher.HashPassword(user,req.NewPassword);user.TokenVersion++;await db.SaveChangesAsync(ct);await audit.WriteAsync(id,"PASSWORD_CHANGE","User",id.ToString(),null,ct);return NoContent();}
 [Authorize,HttpPost("logout")]
 public async Task<ActionResult> Logout(CancellationToken ct){if(!long.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier),out var id))return Unauthorized();var user=await db.UsersSet.FindAsync([id],ct);if(user is null)return Unauthorized();user.TokenVersion++;await db.SaveChangesAsync(ct);await audit.WriteAsync(id,"LOGOUT","User",id.ToString(),null,ct);return NoContent();}
 private sealed record MeAssignment(long Id,string PositionType,long? FacultyId,long? DepartmentId,DateTime EffectiveFrom,DateTime? EffectiveTo,string? Note);
 [Authorize,HttpGet("me")] public async Task<ActionResult> Me(CancellationToken ct){if(!long.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier),out var id))return Unauthorized();var u=await db.UsersSet.AsNoTracking().Include(x=>x.UserRoles).ThenInclude(x=>x.Role).FirstOrDefaultAsync(x=>x.Id==id,ct);if(u is null)return Unauthorized();var teacher=await db.Teachers.AsNoTracking().FirstOrDefaultAsync(x=>x.UserId==id&&x.IsActive,ct);var assignments=new List<MeAssignment>();if(teacher is not null)assignments=await db.ManagementAssignmentsSet.AsNoTracking().Where(x=>x.TeacherId==teacher.Id&&x.IsActive).Select(x=>new MeAssignment(x.Id,x.PositionType,x.FacultyId,x.DepartmentId,x.EffectiveFrom,x.EffectiveTo,x.Note)).ToListAsync(ct);var roles=u.UserRoles.Select(x=>x.Role.Name).ToArray();var isAcademicUser=!roles.Contains("ADMIN");var permissions=new List<string>();if(roles.Contains("ADMIN"))permissions.AddRange(["ACCOUNT_MANAGE","PASSWORD_RESET","ACCOUNT_LOCK","SYSTEM_VIEW","ROOM_MANAGE","CAMERA_MANAGE","CAMERA_TEST","TECH_CATALOG_DEACTIVATE"]);if(roles.Contains("TECH_AI"))permissions.AddRange(["CAMERA_TEST","TECH_CATALOG_DEACTIVATE","FACE_ENROLL_SCOPE"]);if(isAcademicUser&&teacher is not null)permissions.AddRange(["SESSION_VIEW_OWN","SESSION_REPORT_EXPORT_OWN","SESSION_CREATE_SCOPE","STUDENT_EDIT_SCOPE","FACE_ENROLL_SCOPE","CLASS_SECTION_DEACTIVATE_SCOPE","ROSTER_MANAGE_SCOPE"]);if(isAcademicUser&&assignments.Any(x=>x.PositionType=="DEPARTMENT_HEAD"))permissions.AddRange(["DEPARTMENT_VIEW","SUBSTITUTE_ASSIGN","DEPARTMENT_DATA_MANAGE","CLASS_SECTION_CREATE","CLASS_SECTION_UPDATE_SCOPE"]);if(isAcademicUser&&assignments.Any(x=>x.PositionType=="FACULTY_HEAD"))permissions.AddRange(["FACULTY_VIEW","FACULTY_HEAD_TRANSFER","DEPARTMENT_HEAD_ASSIGN","SUBSTITUTE_ASSIGN","STUDENT_CREATE","STUDENT_IMPORT","FACULTY_UPDATE","DEPARTMENT_MANAGE","STUDENT_CLASS_MANAGE","ATTENDANCE_POLICY_MANAGE","DEPARTMENT_DATA_MANAGE","CLASS_SECTION_CREATE","CLASS_SECTION_UPDATE_SCOPE"]);return Ok(new{u.Id,u.UserName,u.Email,u.FullName,u.Status,TeacherId=teacher?.Id,Roles=roles,ManagementAssignments=assignments,FacultyIds=assignments.Where(x=>x.FacultyId!=null).Select(x=>x.FacultyId),DepartmentIds=assignments.Where(x=>x.DepartmentId!=null).Select(x=>x.DepartmentId),Permissions=permissions.Distinct()});}
 private UnauthorizedObjectResult InvalidCredentials()=>Unauthorized(new{code="INVALID_CREDENTIALS",message="Tài khoản hoặc mật khẩu không đúng."});
 private static bool Strong(string p)=>p.Length>=10&&p.Any(char.IsUpper)&&p.Any(char.IsLower)&&p.Any(char.IsDigit)&&p.Any(ch=>!char.IsLetterOrDigit(ch));
}
