using System.Security.Claims; using HTBAM.Api.Support; using HTBAM.Application.DTOs; using HTBAM.Application.Interfaces; using HTBAM.Infrastructure.Data; using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Identity; using Microsoft.AspNetCore.Mvc; using Microsoft.AspNetCore.RateLimiting; using Microsoft.EntityFrameworkCore;
namespace HTBAM.Api.Controllers;
[ApiController,Route("api/auth")]
public sealed class AuthController(AppDbContext db,ITokenService tokens,IAuditService audit):ControllerBase
{
 [HttpPost("login"),EnableRateLimiting("auth")]
 public async Task<ActionResult<LoginResponse>> Login(LoginRequest req,CancellationToken ct){var key=req.UserName.Trim();var user=await db.UsersSet.Include(x=>x.UserRoles).ThenInclude(x=>x.Role).FirstOrDefaultAsync(x=>x.UserName==key||x.Email==key,ct);if(user is null||user.Status!="ACTIVE"){await audit.WriteAsync(user?.Id,"LOGIN_FAILED","User",user?.Id.ToString()??"unknown",new{reason="INVALID_ACCOUNT"},ct);return Unauthorized();}if(new PasswordHasher<HTBAM.Domain.Entities.User>().VerifyHashedPassword(user,user.PasswordHash,req.Password)==PasswordVerificationResult.Failed){await audit.WriteAsync(user.Id,"LOGIN_FAILED","User",user.Id.ToString(),new{reason="BAD_PASSWORD"},ct);return Unauthorized();}user.LastLoginAt=DateTime.UtcNow;await db.SaveChangesAsync(ct);await audit.WriteAsync(user.Id,"LOGIN_SUCCESS","User",user.Id.ToString(),null,ct);return Ok(tokens.Create(user,user.UserRoles.Select(x=>x.Role.Name).ToArray()));}
 public record ChangePasswordRequest(string CurrentPassword,string NewPassword);
 [Authorize,HttpPut("change-password")]
 public async Task<ActionResult> ChangePassword(ChangePasswordRequest req,CancellationToken ct){if(!long.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier),out var id))return Unauthorized();var user=await db.UsersSet.FindAsync([id],ct);if(user is null)return Unauthorized();var hasher=new PasswordHasher<HTBAM.Domain.Entities.User>();if(hasher.VerifyHashedPassword(user,user.PasswordHash,req.CurrentPassword)==PasswordVerificationResult.Failed)return BadRequest("Mật khẩu hiện tại không đúng.");if(!Strong(req.NewPassword))return BadRequest("Mật khẩu >=10 ký tự, có hoa, thường, số và ký tự đặc biệt.");user.PasswordHash=hasher.HashPassword(user,req.NewPassword);user.TokenVersion++;await db.SaveChangesAsync(ct);await audit.WriteAsync(id,"PASSWORD_CHANGE","User",id.ToString(),null,ct);return NoContent();}
 [Authorize,HttpPost("logout")]
 public async Task<ActionResult> Logout(CancellationToken ct){if(!long.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier),out var id))return Unauthorized();var user=await db.UsersSet.FindAsync([id],ct);if(user is null)return Unauthorized();user.TokenVersion++;await db.SaveChangesAsync(ct);await audit.WriteAsync(id,"LOGOUT","User",id.ToString(),null,ct);return NoContent();}
 [Authorize,HttpGet("me")] public async Task<ActionResult> Me(CancellationToken ct){if(!long.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier),out var id))return Unauthorized();var u=await db.UsersSet.AsNoTracking().Include(x=>x.UserRoles).ThenInclude(x=>x.Role).FirstOrDefaultAsync(x=>x.Id==id,ct);return u is null?Unauthorized():Ok(new{u.Id,u.UserName,u.Email,u.FullName,u.Status,Roles=u.UserRoles.Select(x=>x.Role.Name)});}
 private static bool Strong(string p)=>p.Length>=10&&p.Any(char.IsUpper)&&p.Any(char.IsLower)&&p.Any(char.IsDigit)&&p.Any(ch=>!char.IsLetterOrDigit(ch));
}
