using System.Net.Sockets; using System.Text; using HTBAM.Api.Support; using HTBAM.Application.Interfaces; using HTBAM.Domain.Entities; using HTBAM.Infrastructure.Data; using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
namespace HTBAM.Api.Controllers;
[ApiController,Authorize,Route("api/catalogs")]
public sealed class CatalogsController(AppDbContext db,IAuditService audit):ControllerBase
{
 public record FacultyReq(string Code,string Name,string? Note,bool IsActive=true); public record DepartmentReq(string Code,string Name,long FacultyId,string? Note,bool IsActive=true); public record StudentClassReq(string Code,string Name,long FacultyId,int? StartYear,string? Note,bool IsActive=true); public record CourseReq(string Code,string Name,long? DepartmentId,int Credits,string? Note,bool IsActive=true); public record TeacherReq(string TeacherCode,string FullName,string Email,long? UserId,long? DepartmentId,string? Note,bool IsActive=true); public record ClassReq(string Code,string Name,long CourseId,long TeacherId,string Semester,string AcademicYear,string? Note,bool IsActive=true); public record RoomReq(string Code,string Name,string? Location,int Capacity,string? Note,bool IsActive=true); public record CameraReq(string Code,string Name,long RoomId,string RtspUrl,string? Note,bool IsActive=true);

 [HttpGet("faculties")]public async Task<ActionResult> Faculties(CancellationToken ct){var ids=await VisibleFacultyIds(ct);return Ok(await db.FacultiesSet.AsNoTracking().Where(x=>ids.Contains(x.Id)).OrderBy(x=>x.Code).ToListAsync(ct));}
 [HttpPost("faculties"),Authorize(Roles="LECTURER")]public ActionResult AddFaculty(FacultyReq r)=>Forbid();
 [HttpPut("faculties/{id:long}"),Authorize(Roles="LECTURER")]public async Task<ActionResult> UpdateFaculty(long id,FacultyReq r,CancellationToken ct){if(!await AccessScope.CanManageFacultyAsync(db,User,id,ct))return Forbid();var x=await db.FacultiesSet.FindAsync([id],ct);if(x is null)return NotFound();if(await db.FacultiesSet.AnyAsync(y=>y.Id!=id&&y.Code==r.Code.Trim(),ct))return Conflict("Trùng mã khoa.");x.Code=r.Code.Trim();x.Name=r.Name.Trim();x.Note=CleanNote(r.Note);x.IsActive=r.IsActive;await db.SaveChangesAsync(ct);await Audit("FACULTY_UPDATE",id,x.Code,ct);return NoContent();}

 [HttpGet("departments")]public async Task<ActionResult> Departments(CancellationToken ct){var ids=await VisibleDepartmentIds(ct);return Ok(await db.DepartmentsSet.AsNoTracking().Include(x=>x.Faculty).Where(x=>ids.Contains(x.Id)).OrderBy(x=>x.Code).Select(x=>new{x.Id,x.Code,x.Name,x.FacultyId,Faculty=x.Faculty.Name,x.Note,x.IsActive}).ToListAsync(ct));}
 [HttpPost("departments"),Authorize(Roles="LECTURER")]public async Task<ActionResult> AddDepartment(DepartmentReq r,CancellationToken ct){if(!await AccessScope.CanManageFacultyAsync(db,User,r.FacultyId,ct))return Forbid();if(!await db.FacultiesSet.AnyAsync(x=>x.Id==r.FacultyId&&x.IsActive,ct))return BadRequest("Khoa không hợp lệ.");if(await db.DepartmentsSet.AnyAsync(x=>x.Code==r.Code.Trim(),ct))return Conflict("Trùng mã bộ môn.");var x=new Department{Code=r.Code.Trim(),Name=r.Name.Trim(),FacultyId=r.FacultyId,Note=CleanNote(r.Note),IsActive=r.IsActive};db.Add(x);await db.SaveChangesAsync(ct);await Audit("DEPARTMENT_CREATE",x.Id,x.Code,ct);return Ok(x);}
 [HttpPut("departments/{id:long}"),Authorize(Roles="LECTURER")]public async Task<ActionResult> UpdateDepartment(long id,DepartmentReq r,CancellationToken ct){if(!await AccessScope.CanManageDepartmentAsync(db,User,id,ct)||!await AccessScope.CanManageFacultyAsync(db,User,r.FacultyId,ct))return Forbid();var x=await db.DepartmentsSet.FindAsync([id],ct);if(x is null)return NotFound();if(!await db.FacultiesSet.AnyAsync(y=>y.Id==r.FacultyId&&y.IsActive,ct))return BadRequest("Khoa không hợp lệ.");if(await db.DepartmentsSet.AnyAsync(y=>y.Id!=id&&y.Code==r.Code.Trim(),ct))return Conflict("Trùng mã bộ môn.");x.Code=r.Code.Trim();x.Name=r.Name.Trim();x.FacultyId=r.FacultyId;x.Note=CleanNote(r.Note);x.IsActive=r.IsActive;await db.SaveChangesAsync(ct);await Audit("DEPARTMENT_UPDATE",id,x.Code,ct);return NoContent();}

 [HttpGet("student-classes")]public async Task<ActionResult> StudentClasses(CancellationToken ct){var facultyIds=await VisibleFacultyIds(ct);return Ok(await db.StudentClassesSet.AsNoTracking().Include(x=>x.Faculty).Where(x=>facultyIds.Contains(x.FacultyId)).OrderBy(x=>x.Code).Select(x=>new{x.Id,x.Code,x.Name,x.FacultyId,Faculty=x.Faculty.Name,x.StartYear,x.Note,x.IsActive}).ToListAsync(ct));}
 [HttpPost("student-classes"),Authorize(Roles="LECTURER")]public async Task<ActionResult> AddStudentClass(StudentClassReq r,CancellationToken ct){if(!await AccessScope.CanManageFacultyAsync(db,User,r.FacultyId,ct))return Forbid();if(!await db.FacultiesSet.AnyAsync(x=>x.Id==r.FacultyId&&x.IsActive,ct))return BadRequest("Khoa không hợp lệ.");if(await db.StudentClassesSet.AnyAsync(x=>x.Code==r.Code.Trim(),ct))return Conflict("Trùng mã lớp.");var x=new StudentClass{Code=r.Code.Trim(),Name=r.Name.Trim(),FacultyId=r.FacultyId,StartYear=r.StartYear,Note=CleanNote(r.Note),IsActive=r.IsActive};db.Add(x);await db.SaveChangesAsync(ct);await Audit("STUDENT_CLASS_CREATE",x.Id,x.Code,ct);return Ok(x);}
 [HttpPut("student-classes/{id:long}"),Authorize(Roles="LECTURER")]public async Task<ActionResult> UpdateStudentClass(long id,StudentClassReq r,CancellationToken ct){if(!await AccessScope.CanManageStudentClassAsync(db,User,id,ct)||!await AccessScope.CanManageFacultyAsync(db,User,r.FacultyId,ct))return Forbid();var x=await db.StudentClassesSet.FindAsync([id],ct);if(x is null)return NotFound();if(await db.StudentClassesSet.AnyAsync(y=>y.Id!=id&&y.Code==r.Code.Trim(),ct))return Conflict("Trùng mã lớp.");x.Code=r.Code.Trim();x.Name=r.Name.Trim();x.FacultyId=r.FacultyId;x.StartYear=r.StartYear;x.Note=CleanNote(r.Note);x.IsActive=r.IsActive;await db.SaveChangesAsync(ct);await Audit("STUDENT_CLASS_UPDATE",id,x.Code,ct);return NoContent();}

 [HttpGet("courses")]public async Task<ActionResult> Courses(CancellationToken ct){var departments=await VisibleDepartmentIds(ct);return Ok(await db.Courses.AsNoTracking().Where(x=>x.DepartmentId!=null&&departments.Contains(x.DepartmentId.Value)).OrderBy(x=>x.Code).ToListAsync(ct));}
 [HttpPost("courses"),Authorize(Roles="LECTURER")]public async Task<ActionResult> AddCourse(CourseReq r,CancellationToken ct){if(r.DepartmentId is null||!await AccessScope.CanManageDepartmentDataAsync(db,User,r.DepartmentId.Value,ct))return Forbid();if(!await db.DepartmentsSet.AnyAsync(x=>x.Id==r.DepartmentId&&x.IsActive,ct))return BadRequest("Bộ môn không hợp lệ.");if(r.Credits is <1 or >20)return BadRequest("Số tín chỉ không hợp lệ.");if(await db.Courses.AnyAsync(x=>x.Code==r.Code.Trim(),ct))return Conflict("Trùng mã môn.");var x=new Course{Code=r.Code.Trim(),Name=r.Name.Trim(),DepartmentId=r.DepartmentId,Credits=r.Credits,Note=CleanNote(r.Note),IsActive=r.IsActive};db.Add(x);await db.SaveChangesAsync(ct);await Audit("COURSE_CREATE",x.Id,x.Code,ct);return Ok(x);}
 [HttpPut("courses/{id:long}"),Authorize(Roles="LECTURER")]public async Task<ActionResult> UpdateCourse(long id,CourseReq r,CancellationToken ct){var x=await db.Courses.FindAsync([id],ct);if(x is null)return NotFound();if(x.DepartmentId is null||!await AccessScope.CanManageDepartmentDataAsync(db,User,x.DepartmentId.Value,ct)||r.DepartmentId is null||!await AccessScope.CanManageDepartmentDataAsync(db,User,r.DepartmentId.Value,ct))return Forbid();if(await db.Courses.AnyAsync(y=>y.Id!=id&&y.Code==r.Code.Trim(),ct))return Conflict("Trùng mã môn.");x.Code=r.Code.Trim();x.Name=r.Name.Trim();x.DepartmentId=r.DepartmentId;x.Credits=r.Credits;x.Note=CleanNote(r.Note);x.IsActive=r.IsActive;await db.SaveChangesAsync(ct);await Audit("COURSE_UPDATE",id,x.Code,ct);return NoContent();}

 [HttpGet("teachers")]public async Task<ActionResult> Teachers(CancellationToken ct){var tid=await AccessScope.TeacherIdAsync(db,User,ct);var departments=await VisibleDepartmentIds(ct);return Ok(await db.Teachers.AsNoTracking().Where(x=>x.Id==tid||(x.DepartmentId!=null&&departments.Contains(x.DepartmentId.Value))).OrderBy(x=>x.TeacherCode).ToListAsync(ct));}
 [HttpPost("teachers"),Authorize(Roles="LECTURER")]public async Task<ActionResult> AddTeacher(TeacherReq r,CancellationToken ct){if(r.DepartmentId is null||!await AccessScope.CanManageDepartmentDataAsync(db,User,r.DepartmentId.Value,ct))return Forbid();var err=await TeacherValid(r,null,ct);if(err!=null)return err;var x=new Teacher{TeacherCode=r.TeacherCode.Trim(),FullName=r.FullName.Trim(),Email=r.Email.Trim(),UserId=r.UserId,DepartmentId=r.DepartmentId,Note=CleanNote(r.Note),IsActive=r.IsActive};db.Add(x);await db.SaveChangesAsync(ct);await Audit("TEACHER_CREATE",x.Id,x.TeacherCode,ct);return Ok(x);}
 [HttpPut("teachers/{id:long}"),Authorize(Roles="LECTURER")]public async Task<ActionResult> UpdateTeacher(long id,TeacherReq r,CancellationToken ct){var x=await db.Teachers.FindAsync([id],ct);if(x is null)return NotFound();if(x.DepartmentId is null||!await AccessScope.CanManageDepartmentDataAsync(db,User,x.DepartmentId.Value,ct)||r.DepartmentId is null||!await AccessScope.CanManageDepartmentDataAsync(db,User,r.DepartmentId.Value,ct))return Forbid();var err=await TeacherValid(r,id,ct);if(err!=null)return err;x.TeacherCode=r.TeacherCode.Trim();x.FullName=r.FullName.Trim();x.Email=r.Email.Trim();x.UserId=r.UserId;x.DepartmentId=r.DepartmentId;x.Note=CleanNote(r.Note);x.IsActive=r.IsActive;await db.SaveChangesAsync(ct);await Audit("TEACHER_UPDATE",id,x.TeacherCode,ct);return NoContent();}

 [HttpGet("class-sections")]public async Task<ActionResult> Classes(CancellationToken ct){var tid=await AccessScope.TeacherIdAsync(db,User,ct);var permitted=AccessScope.Sessions(db,User,tid).Select(x=>x.ClassSectionId);var q=db.ClassSections.AsNoTracking().Include(x=>x.Course).Include(x=>x.Teacher).Where(x=>x.TeacherId==tid||permitted.Contains(x.Id));return Ok(await q.OrderBy(x=>x.Code).Select(x=>new{x.Id,x.Code,x.Name,x.CourseId,Course=x.Course.Name,x.TeacherId,Teacher=x.Teacher.FullName,x.Semester,x.AcademicYear,x.Note,x.IsActive}).ToListAsync(ct));}
 [HttpPost("class-sections"),Authorize(Roles="LECTURER")]public async Task<ActionResult> AddClass(ClassReq r,CancellationToken ct){var departmentId=await db.Courses.Where(x=>x.Id==r.CourseId&&x.IsActive).Select(x=>x.DepartmentId).FirstOrDefaultAsync(ct);if(departmentId is null||!await AccessScope.CanManageDepartmentDataAsync(db,User,departmentId.Value,ct))return Forbid();if(!await db.Teachers.AnyAsync(x=>x.Id==r.TeacherId&&x.IsActive&&x.DepartmentId==departmentId,ct))return BadRequest("Môn/Giảng viên không hợp lệ.");if(await db.ClassSections.AnyAsync(x=>x.Code==r.Code.Trim(),ct))return Conflict("Trùng mã lớp học phần.");var x=new ClassSection{Code=r.Code.Trim(),Name=r.Name.Trim(),CourseId=r.CourseId,TeacherId=r.TeacherId,Semester=r.Semester.Trim(),AcademicYear=r.AcademicYear.Trim(),Note=CleanNote(r.Note),IsActive=r.IsActive};db.Add(x);await db.SaveChangesAsync(ct);await Audit("CLASS_SECTION_CREATE",x.Id,x.Code,ct);return Ok(x);}
 [HttpPut("class-sections/{id:long}"),Authorize(Roles="LECTURER")]public async Task<ActionResult> UpdateClass(long id,ClassReq r,CancellationToken ct){if(!await AccessScope.CanManageClassSectionAsync(db,User,id,ct))return Forbid();var x=await db.ClassSections.FindAsync([id],ct);if(x is null)return NotFound();var departmentId=await db.Courses.Where(c=>c.Id==r.CourseId&&c.IsActive).Select(c=>c.DepartmentId).FirstOrDefaultAsync(ct);if(departmentId is null||!await AccessScope.CanManageDepartmentDataAsync(db,User,departmentId.Value,ct)||!await db.Teachers.AnyAsync(t=>t.Id==r.TeacherId&&t.IsActive&&t.DepartmentId==departmentId,ct))return Forbid();if(await db.ClassSections.AnyAsync(y=>y.Id!=id&&y.Code==r.Code.Trim(),ct))return Conflict("Trùng mã lớp học phần.");x.Code=r.Code.Trim();x.Name=r.Name.Trim();x.CourseId=r.CourseId;x.TeacherId=r.TeacherId;x.Semester=r.Semester.Trim();x.AcademicYear=r.AcademicYear.Trim();x.Note=CleanNote(r.Note);x.IsActive=r.IsActive;await db.SaveChangesAsync(ct);await Audit("CLASS_SECTION_UPDATE",id,x.Code,ct);return NoContent();}

 [HttpGet("rooms")]public async Task<ActionResult> Rooms(CancellationToken ct)=>Ok(await db.Rooms.AsNoTracking().OrderBy(x=>x.Code).ToListAsync(ct));
 [HttpPost("rooms"),Authorize(Roles="ADMIN")]public async Task<ActionResult> AddRoom(RoomReq r,CancellationToken ct){if(await db.Rooms.AnyAsync(x=>x.Code==r.Code.Trim(),ct))return Conflict("Trùng mã phòng.");var x=new Room{Code=r.Code.Trim(),Name=r.Name.Trim(),Location=r.Location?.Trim(),Capacity=Math.Max(0,r.Capacity),IsActive=r.IsActive};db.Add(x);await db.SaveChangesAsync(ct);await Audit("ROOM_CREATE",x.Id,x.Code,ct);return Ok(x);}
 [HttpPut("rooms/{id:long}"),Authorize(Roles="ADMIN")]public async Task<ActionResult> UpdateRoom(long id,RoomReq r,CancellationToken ct){var x=await db.Rooms.FindAsync([id],ct);if(x is null)return NotFound();if(await db.Rooms.AnyAsync(y=>y.Id!=id&&y.Code==r.Code.Trim(),ct))return Conflict("Trùng mã phòng.");x.Code=r.Code.Trim();x.Name=r.Name.Trim();x.Location=r.Location?.Trim();x.Capacity=Math.Max(0,r.Capacity);x.IsActive=r.IsActive;await db.SaveChangesAsync(ct);await Audit("ROOM_UPDATE",id,x.Code,ct);return NoContent();}

 [HttpGet("cameras")]public async Task<ActionResult> Cameras(CancellationToken ct)=>Ok(await db.CamerasSet.AsNoTracking().Include(x=>x.Room).OrderBy(x=>x.Code).Select(x=>new{x.Id,x.Code,x.Name,x.RoomId,Room=x.Room.Code,x.Status,x.LastHealthCheckAt,x.LastHealthMessage,x.Note,x.IsActive}).ToListAsync(ct));
 [HttpGet("cameras/{id:long}"),Authorize(Roles="ADMIN,TECH_AI")]public async Task<ActionResult> CameraDetail(long id,CancellationToken ct){var x=await db.CamerasSet.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==id,ct);return x is null?NotFound():Ok(x);}
 [HttpPost("cameras"),Authorize(Roles="ADMIN")]public async Task<ActionResult> AddCamera(CameraReq r,CancellationToken ct){var err=await CameraValid(r,null,ct);if(err!=null)return err;var x=new Camera{Code=r.Code.Trim(),Name=r.Name.Trim(),RoomId=r.RoomId,RtspUrl=r.RtspUrl.Trim(),Status="UNKNOWN",Note=CleanNote(r.Note),IsActive=r.IsActive};db.Add(x);await db.SaveChangesAsync(ct);await Audit("CAMERA_CREATE",x.Id,x.Code,ct);return Ok(new{x.Id,x.Code,x.Name,x.RoomId,x.Status,x.Note,x.IsActive});}
 [HttpPut("cameras/{id:long}"),Authorize(Roles="ADMIN")]public async Task<ActionResult> UpdateCamera(long id,CameraReq r,CancellationToken ct){var x=await db.CamerasSet.FindAsync([id],ct);if(x is null)return NotFound();var err=await CameraValid(r,id,ct);if(err!=null)return err;x.Code=r.Code.Trim();x.Name=r.Name.Trim();x.RoomId=r.RoomId;x.RtspUrl=r.RtspUrl.Trim();x.Note=CleanNote(r.Note);x.IsActive=r.IsActive;await db.SaveChangesAsync(ct);await Audit("CAMERA_UPDATE",id,x.Code,ct);return NoContent();}
 [HttpPost("cameras/{id:long}/test"),Authorize(Roles="ADMIN,TECH_AI")]public async Task<ActionResult> TestCamera(long id,CancellationToken ct){var x=await db.CamerasSet.FindAsync([id],ct);if(x is null)return NotFound();var uri=new Uri(x.RtspUrl);var port=uri.Port>0?uri.Port:554;string message;try{using var tcp=new TcpClient();using var timeout=CancellationTokenSource.CreateLinkedTokenSource(ct);timeout.CancelAfter(TimeSpan.FromSeconds(3));await tcp.ConnectAsync(uri.Host,port,timeout.Token);x.Status="ONLINE";message=$"TCP {uri.Host}:{port} reachable";}catch(Exception ex){x.Status="OFFLINE";message=ex.Message.Length>300?ex.Message[..300]:ex.Message;}x.LastHealthCheckAt=DateTime.UtcNow;x.LastHealthMessage=message;await db.SaveChangesAsync(ct);await Audit("CAMERA_TEST",id,x.Code,ct);return Ok(new{x.Id,x.Status,x.LastHealthCheckAt,x.LastHealthMessage});}

 [HttpGet("class-sections/{id:long}/roster")]public async Task<ActionResult> Roster(long id,CancellationToken ct){if(!await AccessScope.CanAccessClassAsync(db,User,id,ct))return Forbid();return Ok(await db.Enrollments.AsNoTracking().Where(x=>x.ClassSectionId==id).Include(x=>x.Student).Select(x=>new{x.StudentId,x.Student.StudentCode,x.Student.FullName,x.Student.Email}).OrderBy(x=>x.StudentCode).ToListAsync(ct));}
 public record RosterReq(long[] StudentIds);
 [HttpPut("class-sections/{id:long}/roster"),Authorize(Roles="LECTURER")]public async Task<ActionResult> SetRoster(long id,RosterReq r,CancellationToken ct){if(!await AccessScope.CanAccessClassAsync(db,User,id,ct))return Forbid();var ids=r.StudentIds.Distinct().ToArray();var valid=await db.StudentsSet.CountAsync(x=>ids.Contains(x.Id)&&x.IsActive,ct);if(valid!=ids.Length)return BadRequest("Roster có sinh viên không hợp lệ.");var old=await db.Enrollments.Where(x=>x.ClassSectionId==id).ToListAsync(ct);db.Enrollments.RemoveRange(old);foreach(var sid in ids)db.Enrollments.Add(new Enrollment{ClassSectionId=id,StudentId=sid});await db.SaveChangesAsync(ct);await Audit("ROSTER_REPLACE",id,$"count={ids.Length}",ct);return NoContent();}
 [HttpPost("class-sections/{id:long}/roster/import-csv"),Authorize(Roles="LECTURER")]public async Task<ActionResult> ImportRoster(long id,IFormFile file,CancellationToken ct){if(!await AccessScope.CanAccessClassAsync(db,User,id,ct))return Forbid();if(file is null||file.Length==0)return BadRequest("Thiếu CSV.");using var sr=new StreamReader(file.OpenReadStream(),Encoding.UTF8,true);var codes=new HashSet<string>(StringComparer.OrdinalIgnoreCase);while(await sr.ReadLineAsync(ct) is string line){var code=line.Split(',',';')[0].Trim().Trim('"');if(code.Contains("MSSV",StringComparison.OrdinalIgnoreCase)||code.Contains("StudentCode",StringComparison.OrdinalIgnoreCase)||string.IsNullOrWhiteSpace(code))continue;codes.Add(code);}var students=await db.StudentsSet.Where(x=>codes.Contains(x.StudentCode)&&x.IsActive).ToListAsync(ct);var missing=codes.Except(students.Select(x=>x.StudentCode),StringComparer.OrdinalIgnoreCase).ToArray();if(missing.Length>0)return BadRequest(new{message="Có MSSV không tồn tại",missing});return await SetRoster(id,new RosterReq(students.Select(x=>x.Id).ToArray()),ct);}

 private async Task<ActionResult?> TeacherValid(TeacherReq r,long? id,CancellationToken ct){if(await db.Teachers.AnyAsync(x=>x.Id!=id&&x.TeacherCode==r.TeacherCode.Trim(),ct))return Conflict("Trùng mã giảng viên.");if(r.UserId!=null){if(!await db.UsersSet.AnyAsync(x=>x.Id==r.UserId&&x.Status=="ACTIVE",ct))return BadRequest("UserId không hợp lệ.");if(await db.Teachers.AnyAsync(x=>x.Id!=id&&x.UserId==r.UserId,ct))return Conflict("Tài khoản đã liên kết giảng viên khác.");}if(r.DepartmentId!=null&&!await db.DepartmentsSet.AnyAsync(x=>x.Id==r.DepartmentId&&x.IsActive,ct))return BadRequest("Bộ môn không hợp lệ.");return null;}
 private async Task<ActionResult?> CameraValid(CameraReq r,long? id,CancellationToken ct){if(await db.CamerasSet.AnyAsync(x=>x.Id!=id&&x.Code==r.Code.Trim(),ct))return Conflict("Trùng mã camera.");if(!await db.Rooms.AnyAsync(x=>x.Id==r.RoomId&&x.IsActive,ct))return BadRequest("Phòng không hợp lệ.");if(!Uri.TryCreate(r.RtspUrl,UriKind.Absolute,out var uri)||uri.Scheme is not("rtsp" or "rtsps"))return BadRequest("RTSP URL không hợp lệ.");return null;}
 [HttpDelete("class-sections/{id:long}/roster/{studentId:long}"),Authorize(Roles="LECTURER")]
 public async Task<ActionResult> RemoveRosterStudent(long id,long studentId,CancellationToken ct){if(!await AccessScope.CanAccessClassAsync(db,User,id,ct))return Forbid();var enrollment=await db.Enrollments.FirstOrDefaultAsync(x=>x.ClassSectionId==id&&x.StudentId==studentId,ct);if(enrollment is null)return NotFound(new{message="Sinh viên không có trong roster này."});db.Enrollments.Remove(enrollment);await db.SaveChangesAsync(ct);await Audit("ROSTER_STUDENT_REMOVE",id,$"studentId={studentId}",ct);return NoContent();}

 [HttpDelete("{resource}/{id:long}"),Authorize(Roles="ADMIN,LECTURER,TECH_AI")]
 public async Task<ActionResult> DeactivateCatalog(string resource,long id,CancellationToken ct)
 {
  if(!await CanDeactivate(resource,id,ct))return Forbid();
  string code;
  switch(resource.ToLowerInvariant())
  {
   case "faculties":
    {var x=await db.FacultiesSet.FindAsync([id],ct);if(x is null)return NotFound(new{message="Khoa không tồn tại."});if(await db.DepartmentsSet.AnyAsync(y=>y.FacultyId==id,ct)||await db.StudentClassesSet.AnyAsync(y=>y.FacultyId==id,ct))return Conflict(new{message=$"Không thể ngừng khoa {x.Code} vì đang có bộ môn hoặc lớp sinh hoạt tham chiếu."});x.IsActive=false;code=x.Code;break;}
   case "departments":
    {var x=await db.DepartmentsSet.FindAsync([id],ct);if(x is null)return NotFound(new{message="Bộ môn không tồn tại."});if(await db.Teachers.AnyAsync(y=>y.DepartmentId==id,ct)||await db.Courses.AnyAsync(y=>y.DepartmentId==id,ct))return Conflict(new{message=$"Không thể ngừng bộ môn {x.Code} vì đang có giảng viên hoặc môn học tham chiếu."});x.IsActive=false;code=x.Code;break;}
   case "student-classes":
    {var x=await db.StudentClassesSet.FindAsync([id],ct);if(x is null)return NotFound(new{message="Lớp sinh hoạt không tồn tại."});if(await db.StudentsSet.AnyAsync(y=>y.StudentClassId==id,ct))return Conflict(new{message=$"Không thể ngừng lớp {x.Code} vì đang có sinh viên tham chiếu."});x.IsActive=false;code=x.Code;break;}
   case "courses":
    {var x=await db.Courses.FindAsync([id],ct);if(x is null)return NotFound(new{message="Môn học không tồn tại."});if(await db.ClassSections.AnyAsync(y=>y.CourseId==id,ct))return Conflict(new{message=$"Không thể ngừng môn {x.Code} vì đang có lớp học phần tham chiếu."});x.IsActive=false;code=x.Code;break;}
   case "teachers":
    {var x=await db.Teachers.FindAsync([id],ct);if(x is null)return NotFound(new{message="Giảng viên không tồn tại."});if(await db.ClassSections.AnyAsync(y=>y.TeacherId==id,ct))return Conflict(new{message=$"Không thể ngừng giảng viên {x.TeacherCode} vì đang phụ trách lớp học phần."});x.IsActive=false;code=x.TeacherCode;break;}
   case "class-sections":
    {var x=await db.ClassSections.FindAsync([id],ct);if(x is null)return NotFound(new{message="Lớp học phần không tồn tại."});if(await db.SessionsSet.AnyAsync(y=>y.ClassSectionId==id,ct)||await db.Enrollments.AnyAsync(y=>y.ClassSectionId==id,ct))return Conflict(new{message=$"Không thể ngừng lớp học phần {x.Code} vì đã có buổi học hoặc roster tham chiếu."});x.IsActive=false;code=x.Code;break;}
   case "rooms":
    {var x=await db.Rooms.FindAsync([id],ct);if(x is null)return NotFound(new{message="Phòng không tồn tại."});if(await db.CamerasSet.AnyAsync(y=>y.RoomId==id,ct)||await db.SessionsSet.AnyAsync(y=>y.RoomId==id,ct))return Conflict(new{message=$"Không thể ngừng phòng {x.Code} vì đang có camera hoặc buổi học tham chiếu."});x.IsActive=false;code=x.Code;break;}
   case "cameras":
    {var x=await db.CamerasSet.FindAsync([id],ct);if(x is null)return NotFound(new{message="Camera không tồn tại."});if(await db.SessionsSet.AnyAsync(y=>y.CameraId==id,ct))return Conflict(new{message=$"Không thể ngừng camera {x.Code} vì đã được gắn với buổi học."});x.IsActive=false;code=x.Code;break;}
   default:return NotFound(new{message="Danh mục không được hỗ trợ."});
  }
  await db.SaveChangesAsync(ct);await Audit("CATALOG_DEACTIVATE",id,code,ct);return NoContent();
 }

 private static string? CleanNote(string? note)=>string.IsNullOrWhiteSpace(note)?null:note.Trim();
 private async Task<bool> CanDeactivate(string resource,long id,CancellationToken ct)
 {
  if(resource is "rooms" or "cameras")return User.IsInRole("ADMIN")||User.IsInRole("TECH_AI");
  if(!User.IsInRole("LECTURER"))return false;
  return resource switch
  {
   "faculties"=>await AccessScope.CanManageFacultyAsync(db,User,id,ct),
   "departments"=>await AccessScope.CanManageDepartmentAsync(db,User,id,ct),
   "student-classes"=>await AccessScope.CanManageStudentClassAsync(db,User,id,ct),
   "courses"=>await CanManageCourse(id,ct),
   "teachers"=>await CanManageTeacher(id,ct),
   "class-sections"=>await AccessScope.CanManageClassSectionAsync(db,User,id,ct),
   _=>false
  };
 }
 private async Task<bool> CanManageCourse(long id,CancellationToken ct){var departmentId=await db.Courses.Where(x=>x.Id==id).Select(x=>x.DepartmentId).FirstOrDefaultAsync(ct);return departmentId!=null&&await AccessScope.CanManageDepartmentDataAsync(db,User,departmentId.Value,ct);}
 private async Task<bool> CanManageTeacher(long id,CancellationToken ct){var departmentId=await db.Teachers.Where(x=>x.Id==id).Select(x=>x.DepartmentId).FirstOrDefaultAsync(ct);return departmentId!=null&&await AccessScope.CanManageDepartmentDataAsync(db,User,departmentId.Value,ct);}
 private async Task<long[]> VisibleDepartmentIds(CancellationToken ct)
 {
  var tid=await AccessScope.TeacherIdAsync(db,User,ct);
  if(tid is not >0)return [];
  var ownDepartmentId=await db.Teachers.AsNoTracking().Where(t=>t.Id==tid&&t.DepartmentId!=null).Select(t=>t.DepartmentId).FirstOrDefaultAsync(ct);
  var assignments=await db.ManagementAssignmentsSet.AsNoTracking().Where(a=>a.TeacherId==tid&&a.IsActive).Select(a=>new{a.DepartmentId,a.FacultyId}).ToListAsync(ct);
  var departmentIds=assignments.Where(x=>x.DepartmentId.HasValue).Select(x=>x.DepartmentId!.Value).ToList();
  if(ownDepartmentId.HasValue)departmentIds.Add(ownDepartmentId.Value);
  var facultyIds=assignments.Where(x=>x.FacultyId.HasValue).Select(x=>x.FacultyId!.Value).Distinct().ToArray();
  var facultyDepartmentIds=await db.DepartmentsSet.AsNoTracking().Where(x=>facultyIds.Contains(x.FacultyId)).Select(x=>x.Id).ToListAsync(ct);
  return departmentIds.Concat(facultyDepartmentIds).Distinct().ToArray();
 }
 private async Task<long[]> VisibleFacultyIds(CancellationToken ct)
 {
  var tid=await AccessScope.TeacherIdAsync(db,User,ct);
  if(tid is not >0)return [];
  var assignments=await db.ManagementAssignmentsSet.AsNoTracking().Where(a=>a.TeacherId==tid&&a.IsActive).Select(a=>new{a.DepartmentId,a.FacultyId}).ToListAsync(ct);
  var explicitFacultyIds=assignments.Where(x=>x.FacultyId.HasValue).Select(x=>x.FacultyId!.Value).ToList();
  var departmentIds=assignments.Where(x=>x.DepartmentId.HasValue).Select(x=>x.DepartmentId!.Value).ToList();
  var ownDepartmentId=await db.Teachers.AsNoTracking().Where(t=>t.Id==tid&&t.DepartmentId!=null).Select(t=>t.DepartmentId).FirstOrDefaultAsync(ct);
  if(ownDepartmentId.HasValue)departmentIds.Add(ownDepartmentId.Value);
  var departmentFacultyIds=await db.DepartmentsSet.AsNoTracking().Where(d=>departmentIds.Contains(d.Id)).Select(d=>d.FacultyId).ToListAsync(ct);
  return explicitFacultyIds.Concat(departmentFacultyIds).Distinct().ToArray();
 }
 private Task Audit(string action,long id,string code,CancellationToken ct)=>audit.WriteAsync(UserContext.Id(User),action,"Catalog",id.ToString(),new{code},ct);
}
