using HTBAM.Api.Support; using HTBAM.Infrastructure.Data; using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
namespace HTBAM.Api.Controllers;
[ApiController,Authorize,Route("api/history")]
public sealed class HistoryController(AppDbContext db):ControllerBase
{
 [HttpGet("sessions/{sessionId:long}/behaviors")]public async Task<ActionResult> Behaviors(long sessionId,[FromQuery]long? studentId,[FromQuery]string? label,[FromQuery]DateTime? from,[FromQuery]DateTime? to,CancellationToken ct){if(!await AccessScope.CanAccessSessionAsync(db,User,sessionId,ct))return Forbid();var q=db.BehaviorEventsSet.AsNoTracking().Where(x=>x.SessionId==sessionId);if(studentId!=null)q=q.Where(x=>x.StudentId==studentId);if(!string.IsNullOrWhiteSpace(label))q=q.Where(x=>x.Label==label.ToUpper());if(from!=null)q=q.Where(x=>x.EndedAt>=from);if(to!=null)q=q.Where(x=>x.StartedAt<to);return Ok(await q.OrderBy(x=>x.StartedAt).Take(10000).ToListAsync(ct));}
 [HttpGet("sessions/{sessionId:long}/attendance")]public async Task<ActionResult> Attendance(long sessionId,CancellationToken ct){if(!await AccessScope.CanAccessSessionAsync(db,User,sessionId,ct))return Forbid();return Ok(await db.AttendanceSet.AsNoTracking().Where(x=>x.SessionId==sessionId).Join(db.StudentsSet,a=>a.StudentId,s=>s.Id,(a,s)=>new{a.Id,a.SessionId,a.StudentId,s.StudentCode,s.FullName,a.PresentSeconds,a.ObservedSeconds,a.PresenceRatio,a.ObservationQuality,a.Status,a.Score,a.PolicyVersion}).OrderBy(x=>x.StudentCode).ToListAsync(ct));}
 [HttpGet("sessions/{sessionId:long}/identities")]public async Task<ActionResult> Identities(long sessionId,CancellationToken ct){if(!await AccessScope.CanAccessSessionAsync(db,User,sessionId,ct))return Forbid();return Ok(await db.StableIdentitiesSet.AsNoTracking().Where(x=>x.SessionId==sessionId).OrderBy(x=>x.FirstSeenAt).Select(x=>new{x.Id,x.StableId,x.StudentId,x.IdentityStatus,x.IdentityConfidence,x.IdentityMargin,x.FirstSeenAt,x.LastSeenAt,x.State,x.CurrentTrackId,x.LastZone,x.SeatHint,x.ModelVersion}).ToListAsync(ct));}
 [HttpGet("identities/{stableIdentityId:long}/evidence")]public async Task<ActionResult> Evidence(long stableIdentityId,CancellationToken ct){var identity=await db.StableIdentitiesSet.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==stableIdentityId,ct);if(identity is null)return NotFound();if(!await AccessScope.CanAccessSessionAsync(db,User,identity.SessionId,ct))return Forbid();var links=await db.IdentityLinksSet.AsNoTracking().Where(x=>x.StableIdentityId==stableIdentityId).OrderBy(x=>x.CreatedAt).ToListAsync(ct);var tracks=await db.TrackSegmentsSet.AsNoTracking().Where(x=>x.StableIdentityId==stableIdentityId).OrderBy(x=>x.StartedAt).ToListAsync(ct);return Ok(new{identity,links,tracks});}
 [HttpGet("students/{studentId:long}")]public async Task<ActionResult> Student(long studentId,[FromQuery]DateTime? from,[FromQuery]DateTime? to,CancellationToken ct){var sessions=db.SessionsSet.AsNoTracking().AsQueryable();if(User.IsInRole("LECTURER")){var tid=await AccessScope.TeacherIdAsync(db,User,ct);sessions=sessions.Where(x=>x.ClassSection.TeacherId==tid);}var permitted=sessions.Select(x=>x.Id);var b=db.BehaviorEventsSet.AsNoTracking().Where(x=>x.StudentId==studentId&&permitted.Contains(x.SessionId));if(from!=null)b=b.Where(x=>x.StartedAt>=from);if(to!=null)b=b.Where(x=>x.StartedAt<to);var events=await b.OrderByDescending(x=>x.StartedAt).Take(5000).ToListAsync(ct);var attendance=await db.AttendanceSet.AsNoTracking().Where(x=>x.StudentId==studentId&&permitted.Contains(x.SessionId)).OrderByDescending(x=>x.SessionId).ToListAsync(ct);return Ok(new{events,attendance});}
}
