using HTBAM.Api.Hubs; using HTBAM.Api.Support; using HTBAM.Application.DTOs; using HTBAM.Application.Interfaces; using HTBAM.Infrastructure.Data; using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.AspNetCore.SignalR; using Microsoft.EntityFrameworkCore;
namespace HTBAM.Api.Controllers;
[ApiController,Authorize(Roles="ADMIN,LECTURER,TECH_AI"),Route("api/sessions")]
public sealed class SessionsController(AppDbContext db,ISessionService sessions,IConfiguration cfg,IAuditService audit,IHubContext<SessionHub> hub):ControllerBase
{
 [HttpGet]public async Task<ActionResult> List([FromQuery]string? status,[FromQuery]long? classSectionId,[FromQuery]DateTime? from,[FromQuery]DateTime? to,CancellationToken ct){var q=db.SessionsSet.AsNoTracking().Include(x=>x.ClassSection).AsQueryable();if(User.IsInRole("LECTURER")){var tid=await AccessScope.TeacherIdAsync(db,User,ct);q=q.Where(x=>x.ClassSection.TeacherId==tid);}if(!string.IsNullOrWhiteSpace(status))q=q.Where(x=>x.Status==status.ToUpper());if(classSectionId!=null)q=q.Where(x=>x.ClassSectionId==classSectionId);if(from!=null)q=q.Where(x=>x.ScheduledStart>=from);if(to!=null)q=q.Where(x=>x.ScheduledStart<to);return Ok(await q.OrderByDescending(x=>x.ScheduledStart).Select(x=>new SessionDto(x.Id,x.ClassSectionId,x.ScheduledStart,x.ScheduledEnd,x.StartedAt,x.EndedAt,x.Status,x.CameraId,x.VideoId,x.AttendancePolicyId)).ToListAsync(ct));}
 [HttpGet("{id:long}")]public async Task<ActionResult> Get(long id,CancellationToken ct){if(!await AccessScope.CanAccessSessionAsync(db,User,id,ct))return Forbid();var x=await db.SessionsSet.AsNoTracking().Include(s=>s.ClassSection).ThenInclude(c=>c.Course).Include(s=>s.ClassSection).ThenInclude(c=>c.Teacher).FirstOrDefaultAsync(s=>s.Id==id,ct);if(x is null)return NotFound();var roster=await db.SessionStudentsSet.AsNoTracking().Where(r=>r.SessionId==id).Include(r=>r.Student).Select(r=>new{r.StudentId,r.Student.StudentCode,r.Student.FullName}).ToListAsync(ct);return Ok(new{x.Id,x.ClassSectionId,ClassSection=x.ClassSection.Code,Course=x.ClassSection.Course.Name,Teacher=x.ClassSection.Teacher.FullName,x.RoomId,x.CameraId,x.VideoId,x.AttendancePolicyId,x.ScheduledStart,x.ScheduledEnd,x.StartedAt,x.EndedAt,x.Status,x.AlertProfile,x.LecturerComment,roster});}
 [HttpPost,Authorize(Roles="ADMIN,LECTURER")]public async Task<ActionResult> Create(CreateSessionRequest r,CancellationToken ct){if(!await AccessScope.CanAccessClassAsync(db,User,r.ClassSectionId,ct))return Forbid();var s=await sessions.CreateAsync(r,ct);await audit.WriteAsync(UserContext.Id(User),"SESSION_CREATE","Session",s.Id.ToString(),new{s.ClassSectionId,s.CameraId,s.VideoId,s.ScheduledStart},ct);return Ok(new{s.Id,s.Status});}
 [HttpPut("{id:long}"),Authorize(Roles="ADMIN,LECTURER")]public async Task<ActionResult> Update(long id,CreateSessionRequest r,CancellationToken ct){if(!await AccessScope.CanAccessSessionAsync(db,User,id,ct)||!await AccessScope.CanAccessClassAsync(db,User,r.ClassSectionId,ct))return Forbid();var current=await db.SessionsSet.FirstOrDefaultAsync(x=>x.Id==id,ct);if(current is null)return NotFound();if(current.Status is not("DRAFT" or "READY"))return Conflict("Chỉ sửa Session DRAFT/READY.");if((r.CameraId is null)==(r.VideoId is null))return BadRequest("Phải chọn đúng một Camera hoặc Video.");if(r.AttendancePolicyId<=0||!await db.AttendancePoliciesSet.AnyAsync(x=>x.Id==r.AttendancePolicyId&&x.IsActive,ct))return BadRequest("AttendancePolicy không hợp lệ.");if(r.ScheduledEnd!=null&&r.ScheduledEnd<=r.ScheduledStart)return BadRequest("ScheduledEnd phải sau ScheduledStart.");if(r.CameraId!=null&&await db.SessionsSet.AnyAsync(x=>x.Id!=id&&x.CameraId==r.CameraId&&x.Status!="CANCELLED"&&x.Status!="COMPLETED"&&x.ScheduledStart<(r.ScheduledEnd??r.ScheduledStart.AddHours(2))&&(x.ScheduledEnd??x.ScheduledStart.AddHours(2))>r.ScheduledStart,ct))return Conflict("Camera bị trùng lịch.");var classRoster=await db.Enrollments.Where(x=>x.ClassSectionId==r.ClassSectionId).Select(x=>x.StudentId).ToListAsync(ct);var roster=(r.StudentIds?.Distinct().ToArray()??Array.Empty<long>());if(roster.Length==0)roster=classRoster.ToArray();if(roster.Except(classRoster).Any())return BadRequest("Roster Session chứa SV không thuộc lớp học phần.");current.ClassSectionId=r.ClassSectionId;current.RoomId=r.RoomId;current.CameraId=r.CameraId;current.VideoId=r.VideoId;current.AttendancePolicyId=r.AttendancePolicyId;current.ScheduledStart=r.ScheduledStart;current.ScheduledEnd=r.ScheduledEnd;current.AlertProfile=string.IsNullOrWhiteSpace(r.AlertProfile)?"DEFAULT":r.AlertProfile.Trim();var old=await db.SessionStudentsSet.Where(x=>x.SessionId==id).ToListAsync(ct);db.SessionStudentsSet.RemoveRange(old);foreach(var sid in roster)db.SessionStudentsSet.Add(new HTBAM.Domain.Entities.SessionStudent{SessionId=id,StudentId=sid});await db.SaveChangesAsync(ct);await audit.WriteAsync(UserContext.Id(User),"SESSION_UPDATE","Session",id.ToString(),new{current.ClassSectionId,current.CameraId,current.VideoId},ct);return NoContent();}
 [HttpPost("{id:long}/cancel"),Authorize(Roles="ADMIN,LECTURER")]public async Task<ActionResult> Cancel(long id,CancellationToken ct){if(!await AccessScope.CanAccessSessionAsync(db,User,id,ct))return Forbid();var s=await db.SessionsSet.FindAsync([id],ct);if(s is null)return NotFound();if(s.Status is not("DRAFT" or "READY"))return Conflict("Chỉ hủy Session chưa chạy.");s.Status="CANCELLED";await db.SaveChangesAsync(ct);await audit.WriteAsync(UserContext.Id(User),"SESSION_CANCEL","Session",id.ToString(),null,ct);return NoContent();}
 [HttpPost("{id:long}/start"),Authorize(Roles="ADMIN,LECTURER")]public async Task<ActionResult> Start(long id,CancellationToken ct){if(!await AccessScope.CanAccessSessionAsync(db,User,id,ct))return Forbid();var baseUrl=cfg["PublicBaseUrl"]??$"{Request.Scheme}://{Request.Host}";var job=await sessions.StartAsync(id,$"{baseUrl.TrimEnd('/')}/api/ai/events",cfg["AiService:CallbackApiKey"]??"",ct);await audit.WriteAsync(UserContext.Id(User),"SESSION_START","Session",id.ToString(),new{job.Id,job.ExternalJobId,job.ModelVersion},ct);await hub.Clients.Group($"session:{id}").SendAsync("sessionStatus",new{sessionId=id,status="RUNNING"},ct);return Ok(new{job.Id,job.ExternalJobId,job.Status,job.ModelVersion});}
 [HttpPost("{id:long}/stop"),Authorize(Roles="ADMIN,LECTURER")]public async Task<ActionResult> Stop(long id,CancellationToken ct){if(!await AccessScope.CanAccessSessionAsync(db,User,id,ct))return Forbid();await sessions.StopAsync(id,ct);await audit.WriteAsync(UserContext.Id(User),"SESSION_STOP","Session",id.ToString(),null,ct);await hub.Clients.Group($"session:{id}").SendAsync("sessionStatus",new{sessionId=id,status="COMPLETED"},ct);return NoContent();}
 [HttpPost("{id:long}/retry-finalize"),Authorize(Roles="ADMIN,LECTURER,TECH_AI")]public async Task<ActionResult> Retry(long id,CancellationToken ct){if(!await AccessScope.CanAccessSessionAsync(db,User,id,ct))return Forbid();await sessions.RetryFinalizeAsync(id,ct);await audit.WriteAsync(UserContext.Id(User),"SESSION_RETRY_FINALIZE","Session",id.ToString(),null,ct);return NoContent();}
 public record CommentReq(string? Comment);[HttpPut("{id:long}/lecturer-comment"),Authorize(Roles="ADMIN,LECTURER")]public async Task<ActionResult> Comment(long id,CommentReq r,CancellationToken ct){if(!await AccessScope.CanAccessSessionAsync(db,User,id,ct))return Forbid();var s=await db.SessionsSet.FindAsync([id],ct);if(s is null)return NotFound();s.LecturerComment=string.IsNullOrWhiteSpace(r.Comment)?null:r.Comment.Trim();await db.SaveChangesAsync(ct);await audit.WriteAsync(UserContext.Id(User),"SESSION_COMMENT","Session",id.ToString(),null,ct);return NoContent();}
 [HttpGet("{id:long}/dashboard")]public async Task<ActionResult> Dashboard(long id,CancellationToken ct){if(!await AccessScope.CanAccessSessionAsync(db,User,id,ct))return Forbid();return Ok(await sessions.DashboardAsync(id,ct));}
}
