import { ChangeDetectionStrategy, Component, HostListener, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../core/api.service';
import { AdminUser } from '../core/models';
import { PageTitleComponent, errorText, fmtDate } from '../shared/ui';

@Component({standalone:true, imports:[FormsModule,PageTitleComponent], changeDetection:ChangeDetectionStrategy.OnPush, template:`
<app-page-title title="Người dùng & phân quyền" subtitle="Quản lý tài khoản kỹ thuật và vai trò hệ thống."><button type="button" (click)="startAdd()">+ Thêm người dùng</button></app-page-title>
@if(error()){<div class="error-box">{{error()}}</div>} @if(message()){<div class="success-box">{{message()}}</div>}
<div class="filter-bar"><label class="grow">Tìm kiếm<input [(ngModel)]="q" (keyup.enter)="load()" placeholder="Tên đăng nhập, email, họ tên" /></label><button type="button" (click)="load()">Tìm kiếm</button><button type="button" class="secondary" (click)="q='';load()">Xóa lọc</button></div>
<section class="card table-card"><div class="table-wrap"><table><thead><tr><th>Tên đăng nhập</th><th>Họ tên</th><th>Email</th><th>Vai trò hệ thống</th><th>Trạng thái</th><th>Đăng nhập gần nhất</th><th>Thao tác</th></tr></thead><tbody>
@if(adding()){<tr><td><input [(ngModel)]="form.userName" placeholder="Tên đăng nhập" /></td><td><input [(ngModel)]="form.fullName" placeholder="Họ tên" /></td><td><input type="email" [(ngModel)]="form.email" placeholder="Email" /></td><td><select [(ngModel)]="form.role"><option value="ADMIN">ADMIN</option><option value="LECTURER">LECTURER</option><option value="TECH_AI">TECH_AI</option></select></td><td><input type="password" [(ngModel)]="form.password" placeholder="Mật khẩu ban đầu" /></td><td>Chưa đăng nhập</td><td><div class="inline-actions"><button type="button" class="small" [disabled]="saving()" (click)="save()">Lưu</button><button type="button" class="secondary small" [disabled]="saving()" (click)="cancelEdit()">Hủy</button></div></td></tr>}
@for(user of items();track user.id){
 @if(editing()?.id===user.id){<tr><td class="cell-title">{{user.userName}}</td><td><input [(ngModel)]="form.fullName" /></td><td><input type="email" [(ngModel)]="form.email" /></td><td><select [(ngModel)]="form.role"><option value="ADMIN">ADMIN</option><option value="LECTURER">LECTURER</option><option value="TECH_AI">TECH_AI</option></select></td><td>{{user.status}}</td><td>{{date(user.lastLoginAt)}}</td><td><div class="inline-actions"><button type="button" class="small" [disabled]="saving()" (click)="save()">Lưu</button><button type="button" class="secondary small" [disabled]="saving()" (click)="cancelEdit()">Hủy</button></div></td></tr>}
 @else{<tr><td class="cell-title">{{user.userName}}</td><td>{{user.fullName}}</td><td>{{user.email||'—'}}</td><td><span class="badge purple">{{user.roles.join(', ')}}</span></td><td><span class="badge" [class.gray]="user.status!=='ACTIVE'">{{user.status==='ACTIVE'?'Hoạt động':'Đã khóa'}}</span></td><td>{{date(user.lastLoginAt)}}</td><td class="menu-cell"><button type="button" class="icon-button" aria-label="Thao tác" (click)="toggleMenu(user.id,$event)">⋮</button>@if(openMenuId()===user.id){<div class="action-menu"><button type="button" (click)="startEdit(user)">Sửa thông tin</button><button type="button" (click)="resetPassword(user)">Reset mật khẩu</button>@if(user.status==='ACTIVE'){<button type="button" (click)="changeStatus(user,'LOCKED')">Khóa tài khoản</button>}@else{<button type="button" (click)="changeStatus(user,'ACTIVE')">Mở khóa</button>}</div>}</td></tr>}
}@empty{<tr><td colspan="7" class="empty">Không có người dùng phù hợp.</td></tr>}
</tbody></table></div></section>
@if(resetUser()){<section class="card action-panel"><div class="card-header"><div><h3>Reset mật khẩu</h3><p>{{resetUser()!.userName}}</p></div></div>@if(resetError()){<div class="error-box">{{resetError()}}</div>}<div class="form-grid"><label>Mật khẩu mới<input [type]="showPassword()?'text':'password'" [(ngModel)]="resetForm.password" /></label><label>Xác nhận mật khẩu<input [type]="showPassword()?'text':'password'" [(ngModel)]="resetForm.confirm" /></label><label class="check span2"><input type="checkbox" [checked]="showPassword()" (change)="showPassword.set(!showPassword())" /> Hiện mật khẩu</label></div><div class="inline-actions"><button type="button" [disabled]="saving()" (click)="submitReset()">Lưu mật khẩu</button><button type="button" class="secondary" [disabled]="saving()" (click)="resetUser.set(null)">Hủy</button></div></section>}`})
export class AdminUsersComponent implements OnInit {
 private readonly api=inject(ApiService); readonly items=signal<AdminUser[]>([]); readonly error=signal(''); readonly message=signal(''); readonly adding=signal(false); readonly editing=signal<AdminUser|null>(null); readonly saving=signal(false); readonly openMenuId=signal<number|null>(null); readonly resetUser=signal<AdminUser|null>(null);readonly resetError=signal('');readonly showPassword=signal(false);readonly date=fmtDate;q='';form=this.emptyForm();resetForm={password:'',confirm:''};
 @HostListener('document:click') closeMenu(){this.openMenuId.set(null)}
 ngOnInit(){this.load()}
 load(){this.api.adminUsers(this.q.trim()).subscribe({next:items=>this.items.set(items),error:error=>this.error.set(errorText(error))})}
 startAdd(){this.editing.set(null);this.form=this.emptyForm();this.adding.set(true)}
 startEdit(user:AdminUser){this.adding.set(false);this.editing.set(user);this.form={userName:user.userName,fullName:user.fullName,email:user.email,role:user.roles[0]||'LECTURER',password:''}}
 cancelEdit(){if(!this.saving()){this.adding.set(false);this.editing.set(null)}}
 toggleMenu(id:number,event:MouseEvent){event.stopPropagation();this.openMenuId.set(this.openMenuId()===id?null:id)}
 save(){if(!this.form.fullName.trim()||(this.adding()&&(!this.form.userName.trim()||!this.form.password))){this.error.set('Vui lòng nhập đủ trường bắt buộc.');return}this.saving.set(true);this.error.set('');const body=this.editing()?{fullName:this.form.fullName.trim(),email:this.form.email.trim(),roles:[this.form.role]}:{userName:this.form.userName.trim(),fullName:this.form.fullName.trim(),email:this.form.email.trim(),password:this.form.password,roles:[this.form.role]};this.api.saveAdminUser(this.editing()?.id??null,body).subscribe({next:()=>{this.saving.set(false);this.cancelEdit();this.message.set('Đã lưu tài khoản.');this.load()},error:error=>{this.error.set(errorText(error));this.saving.set(false)}})}
 resetPassword(user:AdminUser){this.resetUser.set(user);this.resetForm={password:'',confirm:''};this.resetError.set('');this.openMenuId.set(null)}
 submitReset(){const user=this.resetUser();const p=this.resetForm.password;if(!user)return;if(p!==this.resetForm.confirm){this.resetError.set('Mật khẩu xác nhận không khớp.');return}if(p.length<10||!/[A-Z]/.test(p)||!/[a-z]/.test(p)||!/[0-9]/.test(p)||!/[^A-Za-z0-9]/.test(p)){this.resetError.set('Mật khẩu phải có ít nhất 10 ký tự, gồm hoa, thường, số và ký tự đặc biệt.');return}this.saving.set(true);this.api.resetAdminPassword(user.id,p).subscribe({next:()=>{this.saving.set(false);this.resetUser.set(null);this.message.set('Đã reset mật khẩu.')},error:error=>{this.saving.set(false);this.resetError.set(errorText(error))}})}
 changeStatus(user:AdminUser,status:string){this.api.adminStatus(user.id,status).subscribe({next:()=>{this.message.set('Đã cập nhật trạng thái tài khoản.');this.load()},error:error=>this.error.set(errorText(error))})}
 private emptyForm(){return{userName:'',fullName:'',email:'',role:'LECTURER',password:''}}
}
