import { ChangeDetectionStrategy, Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../core/api.service';
import { AdminUser } from '../core/models';
import { ModalComponent, PageTitleComponent, RowActionMenuComponent, apiFieldErrors, errorText, fmtDate, roleText, statusText } from '../shared/ui';

@Component({standalone:true, imports:[FormsModule,ModalComponent,PageTitleComponent,RowActionMenuComponent], changeDetection:ChangeDetectionStrategy.OnPush, template:`
<app-page-title title="Người dùng & phân quyền" subtitle="Quản lý tài khoản kỹ thuật và vai trò hệ thống."><button type="button" (click)="startAdd()">+ Thêm người dùng</button></app-page-title>
@if(error()){<div class="error-box">{{error()}}</div>} @if(message()){<div class="success-box">{{message()}}</div>}
<div class="filter-bar"><label class="grow">Tìm kiếm<input [(ngModel)]="q" (keyup.enter)="load()" placeholder="Tên đăng nhập, email, họ tên" /></label><button type="button" (click)="load()">Tìm kiếm</button><button type="button" class="secondary" (click)="q='';load()">Xóa lọc</button></div>
<section class="card table-card"><div class="table-wrap"><table><thead><tr><th>Tên đăng nhập</th><th>Họ tên</th><th>Email</th><th>Vai trò hệ thống</th><th>Trạng thái</th><th>Đăng nhập gần nhất</th><th>Thao tác</th></tr></thead><tbody>
@for(user of items();track user.id){
 <tr><td class="cell-title">{{user.userName}}</td><td>{{user.fullName}}</td><td>{{user.email||'—'}}</td><td><span class="badge purple">{{roles(user.roles)}}</span></td><td><span class="badge" [class.gray]="user.status!=='ACTIVE'">{{status(user.status)}}</span></td><td>{{date(user.lastLoginAt)}}</td><td class="menu-cell"><app-row-action-menu><button type="button" (click)="startEdit(user)">Sửa thông tin</button><button type="button" (click)="resetPassword(user)">Đặt lại mật khẩu</button>@if(user.status==='ACTIVE'){<button type="button" class="danger" (click)="askStatus(user,'LOCKED')">Khóa tài khoản</button><button type="button" class="danger" (click)="askStatus(user,'INACTIVE')">Ngừng hoạt động</button>}@else if(user.status==='LOCKED'){<button type="button" (click)="askStatus(user,'ACTIVE')">Mở khóa</button><button type="button" class="danger" (click)="askStatus(user,'INACTIVE')">Ngừng hoạt động</button>}@else{<button type="button" (click)="askStatus(user,'ACTIVE')">Kích hoạt lại</button>}</app-row-action-menu></td></tr>
}@empty{<tr><td colspan="7" class="empty">Không có người dùng phù hợp.</td></tr>}
</tbody></table></div></section>
@if(adding()||editing()){
 <app-modal [title]="editing()?'Chỉnh sửa người dùng':'Thêm người dùng'" [busy]="saving()" size="md" (close)="cancelEdit()"><form class="form-grid" (ngSubmit)="save()">@if(formError()){<div class="error-box span2">{{formError()}}</div>}@if(adding()){<label>Tên đăng nhập <span class="required">*</span><input name="userName" [(ngModel)]="form.userName" (input)="clearFieldError('userName')" />@if(fieldErrors()['userName']){<small class="field-error">{{fieldErrors()['userName']}}</small>}</label>}<label>Họ tên <span class="required">*</span><input name="fullName" [(ngModel)]="form.fullName" /></label><label>Email<input name="email" type="email" [(ngModel)]="form.email" (input)="clearFieldError('email')" />@if(fieldErrors()['email']){<small class="field-error">{{fieldErrors()['email']}}</small>}</label><label>Vai trò <span class="required">*</span><select name="role" [(ngModel)]="form.role"><option value="ADMIN">Quản trị hệ thống</option><option value="LECTURER">Giảng viên</option><option value="TECH_AI">Kỹ thuật AI</option></select></label>@if(adding()){<label>Mật khẩu ban đầu <span class="required">*</span><input name="password" type="password" [(ngModel)]="form.password" /></label>}<div class="modal-footer span2" style="margin:0 -20px -20px"><button type="button" class="secondary" [disabled]="saving()" (click)="cancelEdit()">Hủy</button><button type="submit" [disabled]="saving()">{{saving()?'Đang lưu…':'Lưu'}}</button></div></form></app-modal>
}
@if(resetUser()){<app-modal title="Đặt lại mật khẩu" [busy]="saving()" size="md" (close)="closeReset()"><p>Tài khoản: <b>{{resetUser()!.userName}}</b></p>@if(resetError()){<div class="error-box">{{resetError()}}</div>}<div class="form-grid"><label>Mật khẩu mới <span class="required">*</span><input [type]="showPassword()?'text':'password'" [(ngModel)]="resetForm.password" /></label><label>Xác nhận mật khẩu <span class="required">*</span><input [type]="showPassword()?'text':'password'" [(ngModel)]="resetForm.confirm" /></label><label class="check span2"><input type="checkbox" [checked]="showPassword()" (change)="showPassword.set(!showPassword())" /> Hiện mật khẩu</label></div><div class="modal-footer" style="margin:20px -20px -20px"><button type="button" class="secondary" [disabled]="saving()" (click)="closeReset()">Hủy</button><button type="button" [disabled]="saving()" (click)="submitReset()">{{saving()?'Đang lưu…':'Lưu mật khẩu'}}</button></div></app-modal>}
 @if(pendingStatus()){<app-modal [title]="statusActionTitle()" [busy]="saving()" size="sm" (close)="closeStatus()">@if(statusError()){<div class="error-box">{{statusError()}}</div>}<p>Bạn có chắc muốn {{statusActionText()}} tài khoản <b>{{pendingStatus()!.user.userName}}</b> không?</p><div class="modal-footer" style="margin:20px -20px -20px"><button type="button" class="secondary" [disabled]="saving()" (click)="closeStatus()">Hủy</button><button type="button" [class.danger]="pendingStatus()!.status!=='ACTIVE'" [disabled]="saving()" (click)="confirmStatus()">{{saving()?'Đang xử lý…':'Xác nhận'}}</button></div></app-modal>}
`})
export class AdminUsersComponent implements OnInit {
 private readonly api=inject(ApiService); readonly items=signal<AdminUser[]>([]); readonly error=signal(''); readonly message=signal(''); readonly formError=signal('');readonly fieldErrors=signal<Record<string,string>>({}); readonly adding=signal(false); readonly editing=signal<AdminUser|null>(null); readonly saving=signal(false); readonly resetUser=signal<AdminUser|null>(null);readonly resetError=signal('');readonly pendingStatus=signal<{user:AdminUser;status:string}|null>(null);readonly statusError=signal('');readonly showPassword=signal(false);readonly date=fmtDate;readonly status=statusText;q='';form=this.emptyForm();resetForm={password:'',confirm:''};
 ngOnInit(){this.load()}
 load(){this.api.adminUsers(this.q.trim()).subscribe({next:items=>this.items.set(items),error:error=>this.error.set(errorText(error))})}
 startAdd(){this.editing.set(null);this.formError.set('');this.fieldErrors.set({});this.form=this.emptyForm();this.adding.set(true)}
 startEdit(user:AdminUser){this.adding.set(false);this.formError.set('');this.fieldErrors.set({});this.editing.set(user);this.form={userName:user.userName,fullName:user.fullName,email:user.email,role:user.roles[0]||'LECTURER',password:''}}
 cancelEdit(){if(!this.saving()){this.adding.set(false);this.editing.set(null)}}
 save(){if(!this.form.fullName.trim()||(this.adding()&&(!this.form.userName.trim()||!this.form.password))){this.formError.set('Vui lòng nhập đủ trường bắt buộc.');return}this.saving.set(true);this.formError.set('');this.fieldErrors.set({});const body=this.editing()?{fullName:this.form.fullName.trim(),email:this.form.email.trim(),roles:[this.form.role]}:{userName:this.form.userName.trim(),fullName:this.form.fullName.trim(),email:this.form.email.trim(),password:this.form.password,roles:[this.form.role]};this.api.saveAdminUser(this.editing()?.id??null,body).subscribe({next:()=>{this.saving.set(false);this.cancelEdit();this.message.set('Đã lưu tài khoản.');this.load()},error:error=>{this.fieldErrors.set(apiFieldErrors(error));this.formError.set(errorText(error));this.saving.set(false)}})}
 clearFieldError(field:string){this.fieldErrors.update(errors=>{if(!errors[field])return errors;const next={...errors};delete next[field];return next})}
 resetPassword(user:AdminUser){this.resetUser.set(user);this.resetForm={password:'',confirm:''};this.resetError.set('')}
 submitReset(){const user=this.resetUser();const p=this.resetForm.password;if(!user)return;if(p!==this.resetForm.confirm){this.resetError.set('Mật khẩu xác nhận không khớp.');return}if(p.length<10||!/[A-Z]/.test(p)||!/[a-z]/.test(p)||!/[0-9]/.test(p)||!/[^A-Za-z0-9]/.test(p)){this.resetError.set('Mật khẩu phải có ít nhất 10 ký tự, gồm hoa, thường, số và ký tự đặc biệt.');return}this.saving.set(true);this.api.resetAdminPassword(user.id,p).subscribe({next:()=>{this.saving.set(false);this.resetUser.set(null);this.message.set('Đã đặt lại mật khẩu.')},error:error=>{this.saving.set(false);this.resetError.set(errorText(error))}})}
 closeReset(){if(!this.saving())this.resetUser.set(null)}
 askStatus(user:AdminUser,status:string){this.statusError.set('');this.pendingStatus.set({user,status})}
 statusActionTitle(){const status=this.pendingStatus()?.status;return status==='LOCKED'?'Xác nhận khóa tài khoản':status==='INACTIVE'?'Xác nhận ngừng hoạt động':'Xác nhận kích hoạt tài khoản'}
 statusActionText(){const status=this.pendingStatus()?.status;return status==='LOCKED'?'khóa':status==='INACTIVE'?'ngừng hoạt động':'kích hoạt'}
 roles(values:string[]){return values.map(roleText).join(', ')}
 closeStatus(){if(!this.saving())this.pendingStatus.set(null)}
 confirmStatus(){const pending=this.pendingStatus();if(!pending)return;this.saving.set(true);this.api.adminStatus(pending.user.id,pending.status).subscribe({next:()=>{this.saving.set(false);this.pendingStatus.set(null);this.message.set('Đã cập nhật trạng thái tài khoản.');this.load()},error:error=>{this.saving.set(false);this.statusError.set(errorText(error))}})}
 private emptyForm(){return{userName:'',fullName:'',email:'',role:'LECTURER',password:''}}
}
