import { ChangeDetectionStrategy, Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { ApiService } from '../core/api.service';
import { FaceEnrollment, Student } from '../core/models';
import { BackButtonComponent, errorText, statusText } from '../shared/ui';

@Component({standalone:true,imports:[FormsModule,BackButtonComponent],changeDetection:ChangeDetectionStrategy.OnPush,template:`
  <app-back-button to="/students" label="Quay lại danh sách sinh viên" />
  <div class="page-title"><div><h1>Đăng ký khuôn mặt sinh viên</h1><p>Tải ảnh khuôn mặt để huấn luyện dữ liệu nhận diện.</p></div><div class="actions"><button type="button" (click)="start()">Tạo lần đăng ký mới</button></div></div>
  @if(error()){<div class="error-box">{{error()}}</div>}
  <div class="dashboard-grid face-grid">
    <aside>
      <section class="card profile-card">@if(student()){<div class="avatar large">{{student()!.fullName[0]}}</div><h2>{{student()!.fullName}}</h2><p>{{student()!.studentCode}} · {{student()!.studentClass||'Chưa có lớp'}}</p><span class="badge" [class.gray]="!student()!.isActive">{{student()!.isActive?'Hoạt động':'Ngừng hoạt động'}}</span>}</section>
      <section class="card"><h3>Các lần đăng ký</h3>@for(enrollment of list();track enrollment.id){<button type="button" class="list-button" [class.active]="selectedId()===enrollment.id" (click)="select(enrollment.id)"><span>#{{enrollment.id}} · {{statusLabel(enrollment.status)}}</span><small style="margin-left:auto">{{enrollment.uploadedImageCount}} ảnh</small></button>}@empty{<p class="empty">Chưa có lần đăng ký.</p>}</section>
      <section class="card"><h3>Hướng dẫn chụp ảnh</h3><ul style="padding-left:18px;color:#64748b;line-height:1.8;margin:0"><li>Ảnh rõ khuôn mặt, không bị mờ</li><li>Đủ sáng, không ngược sáng</li><li>Không che mặt hoặc đeo kính tối</li><li>Nên có nhiều góc mặt khác nhau</li></ul></section>
    </aside>
    <main>
      <section class="card">@if(detail()){
        <div class="card-header" style="margin:-20px -20px 18px"><div><h3>Lần đăng ký #{{detail().enrollment.id}}</h3><p>{{detail().images.length}} ảnh đã tải lên</p></div><span class="badge blue">{{statusLabel(detail().enrollment.status)}}</span></div>
        @if(canUpload()){
          <div class="form-grid" style="margin-bottom:16px"><label>Góc chụp<select [(ngModel)]="pose"><option value="FRONT">Chính diện</option><option value="LEFT">Nghiêng trái</option><option value="RIGHT">Nghiêng phải</option><option value="UP">Ngẩng lên</option><option value="DOWN">Cúi xuống</option></select></label><label class="drop-zone" style="min-height:110px"><div><div class="upload-icon">⇧</div><strong>{{file?.name||'Chọn ảnh khuôn mặt'}}</strong><small>PNG/JPG, ảnh rõ và đủ sáng</small></div><input type="file" accept="image/*" (change)="file=asFile($event)" /></label></div>
          <div class="inline-actions" style="justify-content:flex-end"><button type="button" [disabled]="!file" (click)="upload()">Tải ảnh</button></div>
        }
        <h3 style="margin-top:20px">Ảnh đã tải lên</h3><div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(130px,1fr));gap:12px;max-width:100%">@for(image of detail().images;track image.id){<article class="panel" style="overflow:hidden"><div style="aspect-ratio:1;background:#f1f5f9;display:grid;place-items:center;color:#94a3b8;font-size:28px">◎</div><div style="padding:10px"><strong style="display:block;font-size:12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">{{image.originalFileName}}</strong><small style="display:block;margin-top:4px;color:#64748b">{{image.capturePose}} · {{image.qualityStatus}}</small></div></article>}@empty{<div class="empty-state" style="grid-column:1/-1"><div><strong>Chưa có ảnh</strong><span>Chọn ảnh để bắt đầu đăng ký.</span></div></div>}</div>
        <div class="form-actions" style="margin-top:20px">@if(canUpload()){<button type="button" (click)="submit()">Gửi sang bước AI</button>}@if(detail().enrollment.status==='PENDING_AI'){<button type="button" (click)="process()">Xử lý bằng AI</button>}</div>
      }@else{<div class="empty-state"><div><strong>Chọn hoặc tạo một lần đăng ký</strong><span>Chi tiết ảnh và trạng thái xử lý sẽ xuất hiện tại đây.</span></div></div>}</section>
    </main>
  </div>
`})
export class FaceEnrollmentComponent implements OnInit{private readonly route=inject(ActivatedRoute);private readonly api=inject(ApiService);readonly studentId=Number(this.route.snapshot.paramMap.get('studentId'));readonly student=signal<Student|null>(null);readonly list=signal<FaceEnrollment[]>([]);readonly detail=signal<any>(null);readonly selectedId=signal<number|null>(null);readonly error=signal('');pose='FRONT';file:File|null=null;ngOnInit(){this.reload()}reload(){this.api.student(this.studentId).subscribe({next:value=>this.student.set(value),error:error=>this.error.set(errorText(error))});this.api.faceList(this.studentId).subscribe({next:items=>{this.list.set(items);if(items[0])this.select(items[0].id)},error:error=>this.error.set(errorText(error))})}select(id:number){this.selectedId.set(id);this.api.faceDetail(this.studentId,id).subscribe({next:value=>this.detail.set(value),error:error=>this.error.set(errorText(error))})}start(){this.api.faceStart(this.studentId).subscribe({next:value=>{this.reload();if(value?.id)this.select(value.id)},error:error=>this.error.set(errorText(error))})}asFile(event:Event){return(event.target as HTMLInputElement).files?.[0]??null}canUpload(){const status=this.detail()?.enrollment.status;return status==='IN_PROGRESS'||status==='NEEDS_RETAKE'}upload(){const id=this.selectedId();if(!this.file||id===null)return;this.api.faceUpload(this.studentId,id,this.file,this.pose).subscribe({next:()=>{this.file=null;this.select(id)},error:error=>this.error.set(errorText(error))})}submit(){const id=this.selectedId();if(id===null)return;this.api.faceSubmit(this.studentId,id).subscribe({next:()=>this.select(id),error:error=>this.error.set(errorText(error))})}process(){const id=this.selectedId();if(id===null)return;this.api.faceProcess(this.studentId,id).subscribe({next:()=>this.select(id),error:error=>this.error.set(errorText(error))})}statusLabel(status:string){return statusText(status)}}
