import { Component, HostListener, OnInit, inject, signal } from '@angular/core';
import { NgTemplateOutlet } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { catchError, forkJoin, Observable, of } from 'rxjs';
import { ApiService } from '../core/api.service';
import { AuthService } from '../core/auth.service';
import { PageTitleComponent, errorText } from '../shared/ui';

type Tab='faculties'|'departments'|'student-classes'|'courses'|'teachers'|'class-sections'|'rooms'|'cameras'|'roster';

@Component({standalone:true,imports:[FormsModule,NgTemplateOutlet,PageTitleComponent],template:`
<app-page-title title="Danh mục & lớp học" subtitle="Dữ liệu học vụ được giới hạn theo phạm vi quản lý.">
 @if(tab()!=='roster'&&canEditTab()){<button type="button" (click)="startAdd()">+ Thêm {{label()}}</button>}
</app-page-title>
@if(error()){<div class="error-box">{{error()}}</div>} @for(refError of refErrorList();track refError.key){<div class="error-box">{{refError.label}}: {{refError.message}}</div>} @if(message()){<div class="success-box">{{message()}}</div>}
<div class="tabs">@for(t of tabs;track t.key){<button type="button" [class.active]="tab()===t.key" (click)="selectTab(t.key)">{{t.label}}</button>}</div>
@if(tab()==='roster'){
 <section class="card"><h3>Roster lớp học phần</h3><div class="toolbar"><label>Lớp học phần<select [(ngModel)]="rosterSectionId" (ngModelChange)="loadRoster()"><option [ngValue]="null">-- Chọn --</option>@for(section of refs.sections;track section.id){<option [ngValue]="section.id">{{section.code}} - {{section.name}}</option>}</select></label></div>
 @if(rosterSectionId){<div class="filter-bar" style="padding:0;border:0;margin-top:16px"><label class="grow">Tìm sinh viên<input [(ngModel)]="rosterQuery" placeholder="MSSV hoặc họ tên" /></label><button type="button" class="secondary" (click)="selectAllRoster()">Chọn tất cả</button><button type="button" class="secondary" (click)="selectedRosterIds.set([])">Bỏ chọn</button></div><div class="roster-grid"><div class="roster-column"><h3>Sinh viên khả dụng</h3>@for(student of availableRosterStudents();track student.id){<label class="check"><input type="checkbox" (change)="toggleRoster(student.id)" />{{student.studentCode}} - {{student.fullName}}</label>}</div><div class="roster-column"><h3>Đã chọn</h3>@for(student of selectedRosterStudents();track student.id){<label class="check"><input type="checkbox" checked (change)="toggleRoster(student.id)" />{{student.studentCode}} - {{student.fullName}}</label>}</div></div><button type="button" [disabled]="saving()" (click)="saveRoster()">Lưu roster</button>}
 </section>
}@else{
 <div class="filter-bar"><label class="grow">Tìm kiếm<input [(ngModel)]="search" [placeholder]="'Tìm trong '+label().toLowerCase()" /></label></div>
 <section class="card table-card"><div class="table-wrap"><table><thead><tr><th>Mã</th><th>Tên / Họ tên</th><th>Thông tin</th><th>Ghi chú</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>
 @if(adding()){<ng-container [ngTemplateOutlet]="editRow" />}
 @for(item of visibleData();track item.id){@if(editingId()===item.id){<ng-container [ngTemplateOutlet]="editRow" />}@else{<tr><td class="cell-title">{{item.code||item.teacherCode}}</td><td>{{item.name||item.fullName}}</td><td>{{info(item)}}</td><td>{{item.note||'—'}}</td><td><span class="badge" [class.gray]="!item.isActive">{{item.isActive?'Hoạt động':'Đã ngừng'}}</span></td><td class="menu-cell"><button type="button" class="icon-button" aria-label="Thao tác" (click)="toggleMenu(item.id,$event)">⋮</button>@if(openMenuId()===item.id){<div class="action-menu">@if(canEditTab()){<button type="button" (click)="startEdit(item)">Sửa</button>}@if(tab()==='cameras'){<button type="button" (click)="testCamera(item)">Test RTSP</button>}@if(canEditTab()&&item.isActive){<button type="button" (click)="deactivate(item)">Ngừng hoạt động</button>}</div>}</td></tr>}}
 @empty{<tr><td colspan="6" class="empty">Không có dữ liệu phù hợp.</td></tr>}
 </tbody></table></div></section>
}
<ng-template #editRow><tr class="editing-row"><td><input [(ngModel)]="form.code" [placeholder]="tab()==='teachers'?'Mã GV':'Mã'" /></td><td><input [(ngModel)]="form.name" placeholder="Tên" /></td><td>
 @if(tab()==='departments'){<select [(ngModel)]="form.facultyId"><option [ngValue]="null">-- Khoa --</option>@for(x of refs.faculties;track x.id){<option [ngValue]="x.id">{{x.code}}</option>}</select>}
 @if(tab()==='student-classes'){<select [(ngModel)]="form.facultyId"><option [ngValue]="null">-- Khoa --</option>@for(x of refs.faculties;track x.id){<option [ngValue]="x.id">{{x.code}}</option>}</select><input type="number" [(ngModel)]="form.startYear" placeholder="Năm bắt đầu" />}
 @if(tab()==='courses'){<select [(ngModel)]="form.departmentId"><option [ngValue]="null">-- Bộ môn --</option>@for(x of refs.departments;track x.id){<option [ngValue]="x.id">{{x.code}}</option>}</select><input type="number" [(ngModel)]="form.credits" min="1" max="20" placeholder="Tín chỉ" />}
 @if(tab()==='teachers'){<input type="email" [(ngModel)]="form.email" placeholder="Email" /><select [(ngModel)]="form.departmentId"><option [ngValue]="null">-- Bộ môn --</option>@for(x of refs.departments;track x.id){<option [ngValue]="x.id">{{x.code}}</option>}</select>}
 @if(tab()==='class-sections'){<select [(ngModel)]="form.courseId"><option [ngValue]="null">-- Môn --</option>@for(x of refs.courses;track x.id){<option [ngValue]="x.id">{{x.code}}</option>}</select><select [(ngModel)]="form.teacherId"><option [ngValue]="null">-- Giảng viên --</option>@for(x of refs.teachers;track x.id){<option [ngValue]="x.id">{{x.teacherCode}}</option>}</select><input [(ngModel)]="form.semester" placeholder="Học kỳ" /><input [(ngModel)]="form.academicYear" placeholder="Năm học" />}
 @if(tab()==='rooms'){<input [(ngModel)]="form.location" placeholder="Vị trí" /><input type="number" [(ngModel)]="form.capacity" min="0" placeholder="Sức chứa" />}
 @if(tab()==='cameras'){<select [(ngModel)]="form.roomId"><option [ngValue]="null">-- Phòng --</option>@for(x of refs.rooms;track x.id){<option [ngValue]="x.id">{{x.code}}</option>}</select><input [(ngModel)]="form.rtspUrl" placeholder="rtsp://..." />}
 </td><td><input [(ngModel)]="form.note" placeholder="Ghi chú" /></td><td><label class="check"><input type="checkbox" [(ngModel)]="form.isActive" /> Hoạt động</label></td><td><div class="inline-actions"><button type="button" class="small" [disabled]="saving()" (click)="save()">Lưu</button><button type="button" class="secondary small" [disabled]="saving()" (click)="cancelEdit()">Hủy</button></div></td></tr>@if(rowError()){<tr><td colspan="6" class="field-error">{{rowError()}}</td></tr>}</ng-template>
`})
export class ManagementComponent implements OnInit{
 readonly auth=inject(AuthService);private readonly api=inject(ApiService);readonly tab=signal<Tab>('faculties');readonly error=signal('');readonly message=signal('');readonly rowError=signal('');readonly refErrors=signal<Record<string,string>>({});readonly adding=signal(false);readonly editingId=signal<number|null>(null);readonly saving=signal(false);readonly openMenuId=signal<number|null>(null);readonly selectedRosterIds=signal<number[]>([]);search='';rosterQuery='';rosterSectionId:number|null=null;form:any={};data:any[]=[];refs:any={faculties:[],departments:[],studentClasses:[],courses:[],teachers:[],sections:[],rooms:[],cameras:[],students:[]};
 readonly tabs:{key:Tab;label:string}[]=[{key:'faculties',label:'Khoa'},{key:'departments',label:'Bộ môn'},{key:'student-classes',label:'Lớp sinh hoạt'},{key:'courses',label:'Môn học'},{key:'teachers',label:'Giảng viên'},{key:'class-sections',label:'Lớp học phần'},{key:'rooms',label:'Phòng học'},{key:'cameras',label:'Camera'},{key:'roster',label:'Roster'}];
 @HostListener('document:click')closeMenu(){this.openMenuId.set(null)} @HostListener('document:keydown.escape')escape(){this.openMenuId.set(null);if(!this.saving())this.cancelEdit()}
 ngOnInit(){this.reloadAll()}
 reloadAll(){this.error.set('');this.refErrors.set({});forkJoin({faculties:this.withFallback('faculties',[],this.api.faculties()),departments:this.withFallback('departments',[],this.api.departments()),studentClasses:this.withFallback('studentClasses',[],this.api.studentClasses()),courses:this.withFallback('courses',[],this.api.courses()),teachers:this.withFallback('teachers',[],this.api.teachers()),sections:this.withFallback('sections',[],this.api.classSections()),rooms:this.withFallback('rooms',[],this.api.rooms()),cameras:this.withFallback('cameras',[],this.api.cameras()),students:this.withFallback('students',[],this.api.students())}).subscribe({next:r=>{this.refs=r;this.setData()},error:e=>this.error.set(errorText(e))})}
 selectTab(tab:Tab){this.tab.set(tab);this.search='';this.cancelEdit();this.setData()}
 setData(){const key=this.tab()==='class-sections'?'sections':this.tab()==='student-classes'?'studentClasses':this.tab();this.data=[...(this.refs[key]||[])]}
 visibleData(){const q=this.search.trim().toLowerCase();return this.data.filter(x=>!q||`${x.code||x.teacherCode||''} ${x.name||x.fullName||''}`.toLowerCase().includes(q))}
 label(){return this.tabs.find(x=>x.key===this.tab())?.label||''}
 refErrorList(){const labels:Record<string,string>={faculties:'Khoa',departments:'Bộ môn',studentClasses:'Lớp sinh hoạt',courses:'Môn học',teachers:'Giảng viên',sections:'Lớp học phần',rooms:'Phòng học',cameras:'Camera',students:'Sinh viên'};return Object.entries(this.refErrors()).map(([key,message])=>({key,label:labels[key]||key,message}))}
 canEditTab(){if(this.tab()==='rooms'||this.tab()==='cameras')return this.auth.isAdmin()||this.auth.user().roles?.includes('TECH_AI');if(this.tab()==='faculties')return !!this.auth.user().permissions?.includes('FACULTY_HEAD_TRANSFER');return this.auth.canManageStructure()}
 startAdd(){this.adding.set(true);this.editingId.set(null);this.rowError.set('');this.form=this.emptyForm()}
 startEdit(item:any){this.adding.set(false);this.editingId.set(item.id);this.rowError.set('');this.form={...this.emptyForm(),...item,code:item.code||item.teacherCode,name:item.name||item.fullName}}
 cancelEdit(){this.adding.set(false);this.editingId.set(null);this.rowError.set('')}
 toggleMenu(id:number,e:MouseEvent){e.stopPropagation();this.openMenuId.set(this.openMenuId()===id?null:id)}
 save(){if(!this.form.code?.trim()||!this.form.name?.trim()){this.rowError.set('Mã và tên là bắt buộc.');return}this.saving.set(true);this.rowError.set('');this.api.saveCatalog(this.tab(),this.editingId(),this.body()).subscribe({next:()=>{this.saving.set(false);this.cancelEdit();this.message.set('Đã lưu dữ liệu.');this.reloadAll()},error:e=>{this.saving.set(false);this.rowError.set(errorText(e))}})}
 deactivate(item:any){this.api.deactivateCatalog(this.tab(),item.id).subscribe({next:()=>{this.message.set('Đã ngừng hoạt động.');this.reloadAll()},error:e=>this.error.set(errorText(e))})}
 testCamera(item:any){this.api.testCamera(item.id).subscribe({next:r=>{this.message.set(`Camera ${item.code}: ${r.status}`);this.reloadAll()},error:e=>this.error.set(errorText(e))})}
 info(x:any){if(this.tab()==='departments')return x.faculty||`Khoa #${x.facultyId}`;if(this.tab()==='student-classes')return `${x.faculty||''} ${x.startYear||''}`;if(this.tab()==='courses')return `${x.credits||0} tín chỉ`;if(this.tab()==='teachers')return x.email||'';if(this.tab()==='class-sections')return `${x.course||''} · ${x.teacher||''}`;if(this.tab()==='rooms')return `${x.location||''} · ${x.capacity||0} chỗ`;if(this.tab()==='cameras')return `${x.room||''} · ${x.status||''}`;return ''}
 body(){const f=this.form;switch(this.tab()){case'faculties':return{code:f.code.trim(),name:f.name.trim(),note:f.note||null,isActive:f.isActive};case'departments':return{code:f.code.trim(),name:f.name.trim(),facultyId:f.facultyId,note:f.note||null,isActive:f.isActive};case'student-classes':return{code:f.code.trim(),name:f.name.trim(),facultyId:f.facultyId,startYear:f.startYear||null,note:f.note||null,isActive:f.isActive};case'courses':return{code:f.code.trim(),name:f.name.trim(),departmentId:f.departmentId,credits:Number(f.credits),note:f.note||null,isActive:f.isActive};case'teachers':return{teacherCode:f.code.trim(),fullName:f.name.trim(),email:(f.email||'').trim(),userId:f.userId||null,departmentId:f.departmentId,note:f.note||null,isActive:f.isActive};case'class-sections':return{code:f.code.trim(),name:f.name.trim(),courseId:f.courseId,teacherId:f.teacherId,semester:(f.semester||'').trim(),academicYear:(f.academicYear||'').trim(),note:f.note||null,isActive:f.isActive};case'rooms':return{code:f.code.trim(),name:f.name.trim(),location:f.location||null,capacity:Number(f.capacity||0),note:f.note||null,isActive:f.isActive};case'cameras':return{code:f.code.trim(),name:f.name.trim(),roomId:f.roomId,rtspUrl:(f.rtspUrl||'').trim(),note:f.note||null,isActive:f.isActive};default:return{}}}
 emptyForm(){return{code:'',name:'',note:'',isActive:true,facultyId:null,departmentId:null,startYear:null,credits:3,email:'',userId:null,courseId:null,teacherId:null,semester:'',academicYear:'',location:'',capacity:0,roomId:null,rtspUrl:''}}
 loadRoster(){if(!this.rosterSectionId){this.selectedRosterIds.set([]);return}this.api.roster(this.rosterSectionId).subscribe({next:r=>this.selectedRosterIds.set(r.map(x=>x.studentId)),error:e=>this.error.set(errorText(e))})}
 availableRosterStudents(){const q=this.rosterQuery.toLowerCase();return this.refs.students.filter((x:any)=>!this.selectedRosterIds().includes(x.id)&&(!q||`${x.studentCode} ${x.fullName}`.toLowerCase().includes(q)))}
 selectedRosterStudents(){return this.refs.students.filter((x:any)=>this.selectedRosterIds().includes(x.id))}
 toggleRoster(id:number){this.selectedRosterIds.update(ids=>ids.includes(id)?ids.filter(x=>x!==id):[...ids,id])}
 selectAllRoster(){this.selectedRosterIds.set(this.refs.students.map((x:any)=>x.id))}
 saveRoster(){if(!this.rosterSectionId)return;this.saving.set(true);this.api.setRoster(this.rosterSectionId,this.selectedRosterIds()).subscribe({next:()=>{this.saving.set(false);this.message.set('Đã lưu roster.')},error:e=>{this.saving.set(false);this.error.set(errorText(e))}})}
 private withFallback<T>(key:string,fallback:T,source:Observable<T>):Observable<T>{return source.pipe(catchError(e=>{this.refErrors.update(errors=>({...errors,[key]:errorText(e)}));return of(fallback)}))}
}
