import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { ApiService } from '../core/api.service';
import { PageTitleComponent, RowActionMenuComponent, behaviorText, errorText, fmtDate, statusText } from '../shared/ui';

@Component({standalone:true,imports:[FormsModule,RouterLink,PageTitleComponent,RowActionMenuComponent],changeDetection:ChangeDetectionStrategy.OnPush,template:`
  <app-page-title title="Tìm kiếm" subtitle="Tìm sinh viên, lớp học phần, buổi học và dữ liệu hành vi." />
  <section class="card"><div class="toolbar"><label class="grow">Từ khóa<input [(ngModel)]="q" (keyup.enter)="load()" placeholder="Nhập MSSV, họ tên, lớp hoặc trạng thái buổi học…" /></label><label>Loại kết quả<select [(ngModel)]="type"><option value="all">Tất cả</option><option value="students">Sinh viên</option><option value="classes">Lớp học phần</option><option value="sessions">Buổi học</option><option value="behaviors">Hành vi</option></select></label><button type="button" [disabled]="loading()" (click)="load()">{{loading()?'Đang tìm…':'Tìm kiếm'}}</button></div></section>
  @if(error()){<div class="error-box">{{error()}}</div>}
  @if(searched()){
    @if(type==='all'||type==='students'){<section class="card table-card"><div class="card-header"><div><h3>Sinh viên</h3><p>{{results()?.students?.length||0}} kết quả</p></div></div><div class="table-wrap"><table><thead><tr><th>MSSV</th><th>Họ tên</th><th>Thao tác</th></tr></thead><tbody>@for(item of results()?.students||[];track item.id){<tr><td class="cell-title">{{item.studentCode}}</td><td>{{item.fullName}}</td><td class="menu-cell"><app-row-action-menu><a [routerLink]="['/students',item.id,'face-enrollment']">Hồ sơ khuôn mặt</a></app-row-action-menu></td></tr>}@empty{<tr><td colspan="3" class="empty">Không có sinh viên phù hợp.</td></tr>}</tbody></table></div></section>}
    @if(type==='all'||type==='classes'){<section class="card table-card"><div class="card-header"><div><h3>Lớp học phần</h3><p>{{results()?.classes?.length||0}} kết quả</p></div></div><div class="table-wrap"><table><thead><tr><th>Mã lớp</th><th>Tên lớp</th><th>Học kỳ</th><th>Năm học</th></tr></thead><tbody>@for(item of results()?.classes||[];track item.id){<tr><td class="cell-title">{{item.code}}</td><td>{{item.name}}</td><td>{{item.semester}}</td><td>{{item.academicYear}}</td></tr>}@empty{<tr><td colspan="4" class="empty">Không có lớp học phần phù hợp.</td></tr>}</tbody></table></div></section>}
    @if(type==='all'||type==='sessions'){<section class="card table-card"><div class="card-header"><div><h3>Buổi học</h3><p>{{results()?.sessions?.length||0}} kết quả</p></div></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>Lớp học phần</th><th>Thời gian</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>@for(item of results()?.sessions||[];track item.id){<tr><td>#{{item.id}}</td><td>{{item.classSection}}</td><td>{{date(item.scheduledStart)}}</td><td><span class="badge blue">{{status(item.status)}}</span></td><td class="menu-cell"><app-row-action-menu><a [routerLink]="['/sessions',item.id]">Chi tiết</a></app-row-action-menu></td></tr>}@empty{<tr><td colspan="5" class="empty">Không có buổi học phù hợp.</td></tr>}</tbody></table></div></section>}
    @if(type==='all'||type==='behaviors'){<section class="card table-card"><div class="card-header"><div><h3>Hành vi</h3><p>{{results()?.behaviors?.length||0}} kết quả</p></div></div><div class="table-wrap"><table><thead><tr><th>Buổi học</th><th>Sinh viên</th><th>Hành vi</th><th>Độ tin cậy</th><th>Thời gian</th></tr></thead><tbody>@for(item of results()?.behaviors||[];track item.id){<tr><td>#{{item.sessionId}}</td><td>{{item.studentId?'#'+item.studentId:'—'}}</td><td><span class="badge purple">{{behavior(item.label)}}</span></td><td>{{item.probability==null?'—':(item.probability*100).toFixed(0)+'%'}}</td><td>{{date(item.startedAt)}}</td></tr>}@empty{<tr><td colspan="5" class="empty">Không có hành vi phù hợp.</td></tr>}</tbody></table></div></section>}
  }@else{<section class="card"><div class="empty-state"><div><strong>Bắt đầu tìm kiếm toàn hệ thống</strong><span>Kết quả sẽ được chia theo từng nhóm dữ liệu.</span></div></div></section>}
`})
export class SearchComponent{private readonly api=inject(ApiService);q='';type='all';readonly results=signal<any>(null);readonly error=signal('');readonly loading=signal(false);readonly searched=signal(false);readonly date=fmtDate;readonly status=statusText;readonly behavior=behaviorText;load(){this.loading.set(true);this.error.set('');this.api.search(`q=${encodeURIComponent(this.q.trim())}`).subscribe({next:(value)=>{this.results.set(value);this.searched.set(true);this.loading.set(false)},error:(error)=>{this.error.set(errorText(error));this.loading.set(false)}})}}
