using HTBAM.Application.DTOs;
using HTBAM.Domain.Entities;
namespace HTBAM.Application.Interfaces;
public interface IAppDbContext
{
 IQueryable<User> Users{get;} IQueryable<Role> Roles{get;} IQueryable<Faculty> Faculties{get;} IQueryable<Department> Departments{get;} IQueryable<StudentClass> StudentClasses{get;} IQueryable<Student> Students{get;} IQueryable<ManagementAssignment> ManagementAssignments{get;} IQueryable<ClassSection> ClassSections{get;} IQueryable<Enrollment> Enrollments{get;} IQueryable<Room> Rooms{get;} IQueryable<Camera> Cameras{get;} IQueryable<Video> Videos{get;} IQueryable<AttendancePolicy> AttendancePolicies{get;} IQueryable<FaceEnrollment> FaceEnrollments{get;} IQueryable<StudentFaceImage> StudentFaceImages{get;} IQueryable<StudentFaceTemplate> StudentFaceTemplates{get;} IQueryable<Session> Sessions{get;} IQueryable<SessionSubstitution> SessionSubstitutions{get;} IQueryable<SessionStudent> SessionStudents{get;} IQueryable<AnalysisJob> AnalysisJobs{get;} IQueryable<StableIdentity> StableIdentities{get;} IQueryable<TrackSegment> TrackSegments{get;} IQueryable<IdentityLink> IdentityLinks{get;} IQueryable<AiEventReceipt> AiEventReceipts{get;} IQueryable<BehaviorEvent> BehaviorEvents{get;} IQueryable<Alert> Alerts{get;} IQueryable<AlertRule> AlertRules{get;} IQueryable<Attendance> Attendance{get;} IQueryable<StudentSessionSummary> StudentSessionSummaries{get;} IQueryable<ClassSessionSummary> ClassSessionSummaries{get;} IQueryable<AuditLog> AuditLogs{get;}
 Task AddAsync<T>(T entity,CancellationToken ct=default) where T:class; void Update<T>(T entity) where T:class; Task<int> SaveChangesAsync(CancellationToken ct=default);
}
public interface IAiClient { Task<StartAiJobResponse> StartAsync(StartAiJobRequest request,CancellationToken ct=default); Task<StopAiJobResponse> StopAsync(string externalJobId,CancellationToken ct=default); Task<AiCapabilitiesResponse> CapabilitiesAsync(CancellationToken ct=default); Task<StartFaceEnrollmentResponse> StartFaceEnrollmentAsync(FaceEnrollmentManifest request,CancellationToken ct=default); Task<bool> HealthAsync(CancellationToken ct=default); }
public interface IObjectStorage { Task EnsureReadyAsync(CancellationToken ct=default); Task PutAsync(string objectKey,Stream stream,long sizeBytes,string contentType,CancellationToken ct=default); Task DeleteAsync(string objectKey,CancellationToken ct=default); Task<string> GetReadUrlAsync(string objectKey,int expirySeconds=900,CancellationToken ct=default); Task<string> GetInternalReadUrlAsync(string objectKey,int expirySeconds=900,CancellationToken ct=default); Task<string> GetInternalWriteUrlAsync(string objectKey,int expirySeconds=900,CancellationToken ct=default); Task<bool> ExistsAsync(string objectKey,CancellationToken ct=default); Task<bool> HealthAsync(CancellationToken ct=default); }
public interface ITokenService { LoginResponse Create(User user,string[] roles); }
public interface ISessionService { Task<Session> CreateAsync(CreateSessionRequest request,CancellationToken ct); Task<AnalysisJob> StartAsync(long sessionId,string callbackUrl,string callbackApiKey,CancellationToken ct); Task StopAsync(long sessionId,CancellationToken ct); Task RetryFinalizeAsync(long sessionId,CancellationToken ct); Task<DashboardSnapshot> DashboardAsync(long sessionId,CancellationToken ct); }
public interface IAiEventService { Task<bool> ProcessAsync(AiEventEnvelope evt,CancellationToken ct); }
public interface IAlertEngine { Task<IReadOnlyList<Alert>> EvaluateAsync(BehaviorEvent behaviorEvent,CancellationToken ct); }
public interface ISummaryService { Task RebuildSessionAsync(long sessionId,CancellationToken ct); }
public interface IAuditService { Task WriteAsync(long? userId,string action,string entityType,string entityId,object? metadata=null,CancellationToken ct=default); }
public interface IFaceEnrollmentService { Task<FaceEnrollment> StartAsync(long studentId,CancellationToken ct); Task<StudentFaceImage> UploadImageAsync(long studentId,long enrollmentId,string originalFileName,string contentType,long sizeBytes,string capturePose,string sourceType,Stream stream,CancellationToken ct); Task<FaceEnrollment> SubmitAsync(long studentId,long enrollmentId,CancellationToken ct); Task CancelAsync(long studentId,long enrollmentId,CancellationToken ct); Task DeleteImageAsync(long studentId,long enrollmentId,long imageId,CancellationToken ct); Task<FaceEnrollmentManifest> BuildManifestAsync(long studentId,long enrollmentId,string callbackUrl,string callbackApiKey,CancellationToken ct); Task ApplyAiResultAsync(long enrollmentId,FaceEnrollmentAiResult result,CancellationToken ct); }
